image: $CI_REGISTRY/qqvp/vcl/containers/kvm-dev-ubuntu:latest

stages:
  - build

.build:
  stage: build
  script:
    - meson setup build/no-vcl --buildtype release -Dplatforms=auto
    - ninja -C build/no-vcl
    - meson setup build/release --prefix `pwd`/build/install --buildtype release -Dplatforms=auto -Dvcl=true
    - ninja -C build/release install
  artifacts:
    when: always
    paths:
      - build/install

build/linux:
  extends: .build
  tags:
    - linux

build/mac:
  extends: .build
  tags:
    - mac
