image: $CI_REGISTRY/qqvp/vcl/containers/vcl-dev-alpine:latest

variables:
  VCL_PROTOCOL_URL: $CI_SERVER_URL/$CI_PROJECT_NAMESPACE/vcl-protocol
  VCL_PROTOCOL_BRANCH: main

stages:
  - fetch
  - build
  - deploy

fetch:
  stage: fetch
  rules:
    - if: $CI_PIPELINE_SOURCE == "pipeline"
  needs:
    - project: qqvp/vcl/vcl-protocol
      job: build
      ref: $UPSTREAM_REF
      artifacts: true
  script:
    - ls build
  artifacts:
    when: on_success
    paths:
      - build

.build:
  stage: build
  needs:
    - job: fetch
      optional: true
  rules:
    - when: always
  script:
    # In case this has been triggered by an upstream merge request,
    # we get the UPSTREAM_REF environment variable
    - |
      if [[ -z "$UPSTREAM_REF" ]]; then
        echo "This is not a downstream job"
        export VCL_PROTOCOL_ARTIFACTS_URL="$VCL_PROTOCOL_URL/-/jobs/artifacts/$VCL_PROTOCOL_BRANCH/download?job=build"
        echo "Downloading $VCL_PROTOCOL_ARTIFACTS_URL"
        curl --location $VCL_PROTOCOL_ARTIFACTS_URL --output vcl-protocol.zip
        unzip vcl-protocol.zip -d $CI_PROJECT_DIR
      fi
    - mkdir -p src/vcl/vcl-protocol
    # This job expects vcl-protocol renderer code to be already available in build
    - mv build/debug/vcl_protocol_renderer_*.h src/vcl/vcl-protocol
    - meson setup build/no-vcl --buildtype release -Dplatforms=auto
    - ninja -C build/no-vcl
    - meson setup build/release --prefix `pwd`/build/install --buildtype release -Dplatforms=auto -Dvcl=true
    - ninja -C build/release install
  artifacts:
    when: on_success
    paths:
      - build/install

build/linux:
  extends:
    - .build
  tags:
    - linux

.deploy:
  stage: deploy
  needs: ["build/linux"]
  trigger:
    project: qqvp/vcl/qemu
    strategy: depend
    branch: vcl

deploy/merge:
  extends: .deploy
  rules:
    - if: $CI_PIPELINE_SOURCE == 'merge_request_event'
  variables:
    UPSTREAM_REF: $CI_MERGE_REQUEST_REF_PATH

deploy/chain:
  extends: .deploy
  rules:
    - if: $CI_PIPELINE_SOURCE == 'pipeline'
  variables:
    UPSTREAM_REF: $CI_COMMIT_REF_NAME
