/* This file is generated by vcl-protocol.  See vcl_protocol_renderer.h. */

/*
 * Copyright 2020 Google LLC
 * Copyright 2024 Qualcomm Innovation Center, Inc. All Rights Reserved.
 * SPDX-License-Identifier: MIT
 */

#ifndef VCL_PROTOCOL_RENDERER_IMAGE_H
#define VCL_PROTOCOL_RENDERER_IMAGE_H

#include "vcl_protocol_renderer_structs.h"

#pragma GCC diagnostic push
#if !defined(__clang__) && defined(__GNUC__) && __GNUC__ >= 12
#pragma GCC diagnostic ignored "-Wdangling-pointer"
#endif
#pragma GCC diagnostic ignored "-Wpointer-arith"
#pragma GCC diagnostic ignored "-Wunused-parameter"

/*
 * These structs/unions/commands are not included
 *
 *   clGetImageInfo
 *   clEnqueueReadImage
 *   clEnqueueWriteImage
 *   clEnqueueFillImage
 *   clEnqueueMapImage
 */

#ifdef CL_API_SUFFIX__VERSION_1_0
static inline void vcl_decode_clGetSupportedImageFormats_args_temp(struct vcl_cs_decoder *dec, struct vcl_command_clGetSupportedImageFormats *args)
{
    vcl_decode_cl_context_lookup(dec, &args->context);
    vcl_decode_cl_mem_flags(dec, &args->flags);
    vcl_decode_cl_mem_object_type(dec, &args->image_type);
    vcl_decode_cl_uint(dec, &args->num_entries);
    if (vcl_decode_simple_pointer(dec)) {
        args->image_formats = vcl_cs_decoder_alloc_temp(dec, sizeof(*args->image_formats));
        if (!args->image_formats) return;
        vcl_decode_cl_image_format_partial_temp(dec, args->image_formats);
    } else {
        args->image_formats = NULL;
        vcl_cs_decoder_set_fatal(dec);
    }
    if (vcl_decode_simple_pointer(dec)) {
        args->num_image_formats = vcl_cs_decoder_alloc_temp(dec, sizeof(*args->num_image_formats));
        if (!args->num_image_formats) return;
    } else {
        args->num_image_formats = NULL;
        vcl_cs_decoder_set_fatal(dec);
    }
}
#endif // CL_API_SUFFIX__VERSION_1_0

#ifdef CL_API_SUFFIX__VERSION_1_0
static inline void vcl_replace_clGetSupportedImageFormats_args_handle(struct vcl_command_clGetSupportedImageFormats *args)
{
    vcl_replace_cl_context_handle(&args->context);
    /* skip args->flags */
    /* skip args->image_type */
    /* skip args->num_entries */
    /* skip args->image_formats */
    /* skip args->num_image_formats */
}
#endif // CL_API_SUFFIX__VERSION_1_0

#ifdef CL_API_SUFFIX__VERSION_1_0
static inline void vcl_encode_clGetSupportedImageFormats_reply(struct vcl_cs_encoder *enc, const struct vcl_command_clGetSupportedImageFormats *args)
{
    vcl_encode_cl_command_type_ext(enc, &(cl_command_type_ext){CL_COMMAND_TYPE_clGetSupportedImageFormats_EXT});

    vcl_encode_cl_int(enc, &args->ret);
    /* skip args->context */
    /* skip args->flags */
    /* skip args->image_type */
    /* skip args->num_entries */
    if (vcl_encode_simple_pointer(enc, args->image_formats))
        vcl_encode_cl_image_format(enc, args->image_formats);
    if (vcl_encode_simple_pointer(enc, args->num_image_formats))
        vcl_encode_cl_uint(enc, args->num_image_formats);
}
#endif // CL_API_SUFFIX__VERSION_1_0

#ifdef CL_API_SUFFIX__VERSION_1_0
static inline void vcl_decode_clEnqueueCopyImage_args_temp(struct vcl_cs_decoder *dec, struct vcl_command_clEnqueueCopyImage *args)
{
    vcl_decode_cl_command_queue_lookup(dec, &args->command_queue);
    vcl_decode_cl_mem_lookup(dec, &args->src_image);
    vcl_decode_cl_mem_lookup(dec, &args->dst_image);
    if (vcl_decode_simple_pointer(dec)) {
        args->src_origin = vcl_cs_decoder_alloc_temp(dec, sizeof(*args->src_origin));
        if (!args->src_origin) return;
        vcl_decode_size_t(dec, (size_t *)args->src_origin);
    } else {
        args->src_origin = NULL;
        vcl_cs_decoder_set_fatal(dec);
    }
    if (vcl_decode_simple_pointer(dec)) {
        args->dst_origin = vcl_cs_decoder_alloc_temp(dec, sizeof(*args->dst_origin));
        if (!args->dst_origin) return;
        vcl_decode_size_t(dec, (size_t *)args->dst_origin);
    } else {
        args->dst_origin = NULL;
        vcl_cs_decoder_set_fatal(dec);
    }
    if (vcl_decode_simple_pointer(dec)) {
        args->region = vcl_cs_decoder_alloc_temp(dec, sizeof(*args->region));
        if (!args->region) return;
        vcl_decode_size_t(dec, (size_t *)args->region);
    } else {
        args->region = NULL;
        vcl_cs_decoder_set_fatal(dec);
    }
    vcl_decode_cl_uint(dec, &args->num_events_in_wait_list);
    if (vcl_decode_simple_pointer(dec)) {
        args->event_wait_list = vcl_cs_decoder_alloc_temp(dec, sizeof(*args->event_wait_list));
        if (!args->event_wait_list) return;
        vcl_decode_cl_event_lookup(dec, (cl_event *)args->event_wait_list);
    } else {
        args->event_wait_list = NULL;
        vcl_cs_decoder_set_fatal(dec);
    }
    if (vcl_decode_simple_pointer(dec)) {
        args->event = vcl_cs_decoder_alloc_temp(dec, sizeof(*args->event));
        if (!args->event) return;
        vcl_decode_cl_event_temp(dec, args->event);
    } else {
        args->event = NULL;
        vcl_cs_decoder_set_fatal(dec);
    }
}
#endif // CL_API_SUFFIX__VERSION_1_0

#ifdef CL_API_SUFFIX__VERSION_1_0
static inline void vcl_replace_clEnqueueCopyImage_args_handle(struct vcl_command_clEnqueueCopyImage *args)
{
    vcl_replace_cl_command_queue_handle(&args->command_queue);
    vcl_replace_cl_mem_handle(&args->src_image);
    vcl_replace_cl_mem_handle(&args->dst_image);
    /* skip args->src_origin */
    /* skip args->dst_origin */
    /* skip args->region */
    /* skip args->num_events_in_wait_list */
    if (args->event_wait_list)
        vcl_replace_cl_event_handle((cl_event *)args->event_wait_list);
    /* skip args->event */
}
#endif // CL_API_SUFFIX__VERSION_1_0

#ifdef CL_API_SUFFIX__VERSION_1_0
static inline void vcl_encode_clEnqueueCopyImage_reply(struct vcl_cs_encoder *enc, const struct vcl_command_clEnqueueCopyImage *args)
{
    vcl_encode_cl_command_type_ext(enc, &(cl_command_type_ext){CL_COMMAND_TYPE_clEnqueueCopyImage_EXT});

    vcl_encode_cl_int(enc, &args->ret);
    /* skip args->command_queue */
    /* skip args->src_image */
    /* skip args->dst_image */
    /* skip args->src_origin */
    /* skip args->dst_origin */
    /* skip args->region */
    /* skip args->num_events_in_wait_list */
    /* skip args->event_wait_list */
    if (vcl_encode_simple_pointer(enc, args->event))
        vcl_encode_cl_event(enc, args->event);
}
#endif // CL_API_SUFFIX__VERSION_1_0

#ifdef CL_API_SUFFIX__VERSION_1_0
static inline void vcl_decode_clEnqueueCopyImageToBuffer_args_temp(struct vcl_cs_decoder *dec, struct vcl_command_clEnqueueCopyImageToBuffer *args)
{
    vcl_decode_cl_command_queue_lookup(dec, &args->command_queue);
    vcl_decode_cl_mem_lookup(dec, &args->src_image);
    vcl_decode_cl_mem_lookup(dec, &args->dst_buffer);
    if (vcl_decode_simple_pointer(dec)) {
        args->src_origin = vcl_cs_decoder_alloc_temp(dec, sizeof(*args->src_origin));
        if (!args->src_origin) return;
        vcl_decode_size_t(dec, (size_t *)args->src_origin);
    } else {
        args->src_origin = NULL;
        vcl_cs_decoder_set_fatal(dec);
    }
    if (vcl_decode_simple_pointer(dec)) {
        args->region = vcl_cs_decoder_alloc_temp(dec, sizeof(*args->region));
        if (!args->region) return;
        vcl_decode_size_t(dec, (size_t *)args->region);
    } else {
        args->region = NULL;
        vcl_cs_decoder_set_fatal(dec);
    }
    vcl_decode_size_t(dec, &args->dst_offset);
    vcl_decode_cl_uint(dec, &args->num_events_in_wait_list);
    if (vcl_decode_simple_pointer(dec)) {
        args->event_wait_list = vcl_cs_decoder_alloc_temp(dec, sizeof(*args->event_wait_list));
        if (!args->event_wait_list) return;
        vcl_decode_cl_event_lookup(dec, (cl_event *)args->event_wait_list);
    } else {
        args->event_wait_list = NULL;
        vcl_cs_decoder_set_fatal(dec);
    }
    if (vcl_decode_simple_pointer(dec)) {
        args->event = vcl_cs_decoder_alloc_temp(dec, sizeof(*args->event));
        if (!args->event) return;
        vcl_decode_cl_event_temp(dec, args->event);
    } else {
        args->event = NULL;
        vcl_cs_decoder_set_fatal(dec);
    }
}
#endif // CL_API_SUFFIX__VERSION_1_0

#ifdef CL_API_SUFFIX__VERSION_1_0
static inline void vcl_replace_clEnqueueCopyImageToBuffer_args_handle(struct vcl_command_clEnqueueCopyImageToBuffer *args)
{
    vcl_replace_cl_command_queue_handle(&args->command_queue);
    vcl_replace_cl_mem_handle(&args->src_image);
    vcl_replace_cl_mem_handle(&args->dst_buffer);
    /* skip args->src_origin */
    /* skip args->region */
    /* skip args->dst_offset */
    /* skip args->num_events_in_wait_list */
    if (args->event_wait_list)
        vcl_replace_cl_event_handle((cl_event *)args->event_wait_list);
    /* skip args->event */
}
#endif // CL_API_SUFFIX__VERSION_1_0

#ifdef CL_API_SUFFIX__VERSION_1_0
static inline void vcl_encode_clEnqueueCopyImageToBuffer_reply(struct vcl_cs_encoder *enc, const struct vcl_command_clEnqueueCopyImageToBuffer *args)
{
    vcl_encode_cl_command_type_ext(enc, &(cl_command_type_ext){CL_COMMAND_TYPE_clEnqueueCopyImageToBuffer_EXT});

    vcl_encode_cl_int(enc, &args->ret);
    /* skip args->command_queue */
    /* skip args->src_image */
    /* skip args->dst_buffer */
    /* skip args->src_origin */
    /* skip args->region */
    /* skip args->dst_offset */
    /* skip args->num_events_in_wait_list */
    /* skip args->event_wait_list */
    if (vcl_encode_simple_pointer(enc, args->event))
        vcl_encode_cl_event(enc, args->event);
}
#endif // CL_API_SUFFIX__VERSION_1_0

#ifdef CL_API_SUFFIX__VERSION_1_0
static inline void vcl_decode_clEnqueueCopyBufferToImage_args_temp(struct vcl_cs_decoder *dec, struct vcl_command_clEnqueueCopyBufferToImage *args)
{
    vcl_decode_cl_command_queue_lookup(dec, &args->command_queue);
    vcl_decode_cl_mem_lookup(dec, &args->src_buffer);
    vcl_decode_cl_mem_lookup(dec, &args->dst_image);
    vcl_decode_size_t(dec, &args->src_offset);
    if (vcl_decode_simple_pointer(dec)) {
        args->dst_origin = vcl_cs_decoder_alloc_temp(dec, sizeof(*args->dst_origin));
        if (!args->dst_origin) return;
        vcl_decode_size_t(dec, (size_t *)args->dst_origin);
    } else {
        args->dst_origin = NULL;
        vcl_cs_decoder_set_fatal(dec);
    }
    if (vcl_decode_simple_pointer(dec)) {
        args->region = vcl_cs_decoder_alloc_temp(dec, sizeof(*args->region));
        if (!args->region) return;
        vcl_decode_size_t(dec, (size_t *)args->region);
    } else {
        args->region = NULL;
        vcl_cs_decoder_set_fatal(dec);
    }
    vcl_decode_cl_uint(dec, &args->num_events_in_wait_list);
    if (vcl_decode_simple_pointer(dec)) {
        args->event_wait_list = vcl_cs_decoder_alloc_temp(dec, sizeof(*args->event_wait_list));
        if (!args->event_wait_list) return;
        vcl_decode_cl_event_lookup(dec, (cl_event *)args->event_wait_list);
    } else {
        args->event_wait_list = NULL;
        vcl_cs_decoder_set_fatal(dec);
    }
    if (vcl_decode_simple_pointer(dec)) {
        args->event = vcl_cs_decoder_alloc_temp(dec, sizeof(*args->event));
        if (!args->event) return;
        vcl_decode_cl_event_temp(dec, args->event);
    } else {
        args->event = NULL;
        vcl_cs_decoder_set_fatal(dec);
    }
}
#endif // CL_API_SUFFIX__VERSION_1_0

#ifdef CL_API_SUFFIX__VERSION_1_0
static inline void vcl_replace_clEnqueueCopyBufferToImage_args_handle(struct vcl_command_clEnqueueCopyBufferToImage *args)
{
    vcl_replace_cl_command_queue_handle(&args->command_queue);
    vcl_replace_cl_mem_handle(&args->src_buffer);
    vcl_replace_cl_mem_handle(&args->dst_image);
    /* skip args->src_offset */
    /* skip args->dst_origin */
    /* skip args->region */
    /* skip args->num_events_in_wait_list */
    if (args->event_wait_list)
        vcl_replace_cl_event_handle((cl_event *)args->event_wait_list);
    /* skip args->event */
}
#endif // CL_API_SUFFIX__VERSION_1_0

#ifdef CL_API_SUFFIX__VERSION_1_0
static inline void vcl_encode_clEnqueueCopyBufferToImage_reply(struct vcl_cs_encoder *enc, const struct vcl_command_clEnqueueCopyBufferToImage *args)
{
    vcl_encode_cl_command_type_ext(enc, &(cl_command_type_ext){CL_COMMAND_TYPE_clEnqueueCopyBufferToImage_EXT});

    vcl_encode_cl_int(enc, &args->ret);
    /* skip args->command_queue */
    /* skip args->src_buffer */
    /* skip args->dst_image */
    /* skip args->src_offset */
    /* skip args->dst_origin */
    /* skip args->region */
    /* skip args->num_events_in_wait_list */
    /* skip args->event_wait_list */
    if (vcl_encode_simple_pointer(enc, args->event))
        vcl_encode_cl_event(enc, args->event);
}
#endif // CL_API_SUFFIX__VERSION_1_0

#ifdef CL_API_SUFFIX__VERSION_1_2
static inline void vcl_decode_clCreateImageMESA_args_temp(struct vcl_cs_decoder *dec, struct vcl_command_clCreateImageMESA *args)
{
    vcl_decode_cl_context_lookup(dec, &args->context);
    vcl_decode_cl_mem_flags(dec, &args->flags);
    if (vcl_decode_simple_pointer(dec)) {
        args->image_format = vcl_cs_decoder_alloc_temp(dec, sizeof(*args->image_format));
        if (!args->image_format) return;
        vcl_decode_cl_image_format_temp(dec, (cl_image_format *)args->image_format);
    } else {
        args->image_format = NULL;
        vcl_cs_decoder_set_fatal(dec);
    }
    if (vcl_decode_simple_pointer(dec)) {
        args->image_desc = vcl_cs_decoder_alloc_temp(dec, sizeof(*args->image_desc));
        if (!args->image_desc) return;
        vcl_decode_cl_image_desc_temp(dec, (cl_image_desc *)args->image_desc);
    } else {
        args->image_desc = NULL;
        vcl_cs_decoder_set_fatal(dec);
    }
    vcl_decode_size_t(dec, &args->size);
    if (vcl_peek_array_size(dec)) {
        const size_t array_size = vcl_decode_array_size(dec, args->size);
        args->host_ptr = vcl_cs_decoder_alloc_temp(dec, array_size);
        if (!args->host_ptr) return;
        vcl_decode_blob_array(dec, (void *)args->host_ptr, array_size);
    } else {
        vcl_decode_array_size(dec, args->size);
        args->host_ptr = NULL;
    }
    if (vcl_decode_simple_pointer(dec)) {
        args->image = vcl_cs_decoder_alloc_temp(dec, sizeof(*args->image));
        if (!args->image) return;
        vcl_decode_cl_mem_temp(dec, args->image);
    } else {
        args->image = NULL;
        vcl_cs_decoder_set_fatal(dec);
    }
}
#endif // CL_API_SUFFIX__VERSION_1_2

#ifdef CL_API_SUFFIX__VERSION_1_2
static inline void vcl_replace_clCreateImageMESA_args_handle(struct vcl_command_clCreateImageMESA *args)
{
    vcl_replace_cl_context_handle(&args->context);
    /* skip args->flags */
    if (args->image_format)
        vcl_replace_cl_image_format_handle((cl_image_format *)args->image_format);
    if (args->image_desc)
        vcl_replace_cl_image_desc_handle((cl_image_desc *)args->image_desc);
    /* skip args->size */
    /* skip args->host_ptr */
    /* skip args->image */
}
#endif // CL_API_SUFFIX__VERSION_1_2

#ifdef CL_API_SUFFIX__VERSION_1_2
static inline void vcl_encode_clCreateImageMESA_reply(struct vcl_cs_encoder *enc, const struct vcl_command_clCreateImageMESA *args)
{
    vcl_encode_cl_command_type_ext(enc, &(cl_command_type_ext){CL_COMMAND_TYPE_clCreateImageMESA_EXT});

    vcl_encode_cl_int(enc, &args->ret);
    /* skip args->context */
    /* skip args->flags */
    /* skip args->image_format */
    /* skip args->image_desc */
    /* skip args->size */
    /* skip args->host_ptr */
    if (vcl_encode_simple_pointer(enc, args->image))
        vcl_encode_cl_mem(enc, args->image);
}
#endif // CL_API_SUFFIX__VERSION_1_2

#ifdef CL_API_SUFFIX__VERSION_3_0
static inline void vcl_decode_clCreateImageWithPropertiesMESA_args_temp(struct vcl_cs_decoder *dec, struct vcl_command_clCreateImageWithPropertiesMESA *args)
{
    vcl_decode_cl_context_lookup(dec, &args->context);
    if (vcl_peek_array_size(dec)) {
        const size_t null_terminated_array_size = vcl_decode_array_size_unchecked(dec);
        args->properties = vcl_cs_decoder_alloc_temp_array(dec, sizeof(*args->properties), null_terminated_array_size);
        if (!args->properties) return;
        vcl_decode_cl_mem_properties_array(dec, (cl_mem_properties *)args->properties, null_terminated_array_size);
    } else {
        vcl_decode_array_size_unchecked(dec);
        args->properties = NULL;
    }
    vcl_decode_cl_mem_flags(dec, &args->flags);
    if (vcl_decode_simple_pointer(dec)) {
        args->image_format = vcl_cs_decoder_alloc_temp(dec, sizeof(*args->image_format));
        if (!args->image_format) return;
        vcl_decode_cl_image_format_temp(dec, (cl_image_format *)args->image_format);
    } else {
        args->image_format = NULL;
        vcl_cs_decoder_set_fatal(dec);
    }
    if (vcl_decode_simple_pointer(dec)) {
        args->image_desc = vcl_cs_decoder_alloc_temp(dec, sizeof(*args->image_desc));
        if (!args->image_desc) return;
        vcl_decode_cl_image_desc_temp(dec, (cl_image_desc *)args->image_desc);
    } else {
        args->image_desc = NULL;
        vcl_cs_decoder_set_fatal(dec);
    }
    vcl_decode_size_t(dec, &args->size);
    if (vcl_peek_array_size(dec)) {
        const size_t array_size = vcl_decode_array_size(dec, args->size);
        args->host_ptr = vcl_cs_decoder_alloc_temp(dec, array_size);
        if (!args->host_ptr) return;
        vcl_decode_blob_array(dec, (void *)args->host_ptr, array_size);
    } else {
        vcl_decode_array_size(dec, args->size);
        args->host_ptr = NULL;
    }
    if (vcl_decode_simple_pointer(dec)) {
        args->image = vcl_cs_decoder_alloc_temp(dec, sizeof(*args->image));
        if (!args->image) return;
        vcl_decode_cl_mem_temp(dec, args->image);
    } else {
        args->image = NULL;
        vcl_cs_decoder_set_fatal(dec);
    }
}
#endif // CL_API_SUFFIX__VERSION_3_0

#ifdef CL_API_SUFFIX__VERSION_3_0
static inline void vcl_replace_clCreateImageWithPropertiesMESA_args_handle(struct vcl_command_clCreateImageWithPropertiesMESA *args)
{
    vcl_replace_cl_context_handle(&args->context);
    /* skip args->properties */
    /* skip args->flags */
    if (args->image_format)
        vcl_replace_cl_image_format_handle((cl_image_format *)args->image_format);
    if (args->image_desc)
        vcl_replace_cl_image_desc_handle((cl_image_desc *)args->image_desc);
    /* skip args->size */
    /* skip args->host_ptr */
    /* skip args->image */
}
#endif // CL_API_SUFFIX__VERSION_3_0

#ifdef CL_API_SUFFIX__VERSION_3_0
static inline void vcl_encode_clCreateImageWithPropertiesMESA_reply(struct vcl_cs_encoder *enc, const struct vcl_command_clCreateImageWithPropertiesMESA *args)
{
    vcl_encode_cl_command_type_ext(enc, &(cl_command_type_ext){CL_COMMAND_TYPE_clCreateImageWithPropertiesMESA_EXT});

    vcl_encode_cl_int(enc, &args->ret);
    /* skip args->context */
    /* skip args->properties */
    /* skip args->flags */
    /* skip args->image_format */
    /* skip args->image_desc */
    /* skip args->size */
    /* skip args->host_ptr */
    if (vcl_encode_simple_pointer(enc, args->image))
        vcl_encode_cl_mem(enc, args->image);
}
#endif // CL_API_SUFFIX__VERSION_3_0


static inline void vcl_dispatch_clGetSupportedImageFormats(struct vcl_dispatch_context *ctx, cl_command_flags_ext flags)
{
#ifdef CL_API_SUFFIX__VERSION_1_0
    struct vcl_command_clGetSupportedImageFormats args;

    if (!ctx->dispatch_clGetSupportedImageFormats) {
        vcl_cs_decoder_set_fatal(ctx->decoder);
        return;
    }

    vcl_decode_clGetSupportedImageFormats_args_temp(ctx->decoder, &args);
    if (!args.context) {
        vcl_cs_decoder_set_fatal(ctx->decoder);
        return;
    }

    if (!vcl_cs_decoder_get_fatal(ctx->decoder))
        ctx->dispatch_clGetSupportedImageFormats(ctx, &args);

#ifdef DEBUG
    if (!vcl_cs_decoder_get_fatal(ctx->decoder) && vcl_dispatch_should_log_result(args.ret))
        vcl_dispatch_debug_log(ctx, "clGetSupportedImageFormats returned %d", args.ret);
#endif

    if ((flags & CL_COMMAND_GENERATE_REPLY_BIT_EXT) && !vcl_cs_decoder_get_fatal(ctx->decoder))
        vcl_encode_clGetSupportedImageFormats_reply(ctx->encoder, &args);

    vcl_cs_decoder_reset_temp_pool(ctx->decoder);
#else
    vcl_dispatch_debug_log(ctx, "CL_API_SUFFIX__VERSION_1_0 not available for clGetSupportedImageFormats");
    vcl_cs_decoder_set_fatal(ctx->decoder);
#endif // CL_API_SUFFIX__VERSION_1_0
}


static inline void vcl_dispatch_clEnqueueCopyImage(struct vcl_dispatch_context *ctx, cl_command_flags_ext flags)
{
#ifdef CL_API_SUFFIX__VERSION_1_0
    struct vcl_command_clEnqueueCopyImage args;

    if (!ctx->dispatch_clEnqueueCopyImage) {
        vcl_cs_decoder_set_fatal(ctx->decoder);
        return;
    }

    vcl_decode_clEnqueueCopyImage_args_temp(ctx->decoder, &args);
    if (!args.command_queue) {
        vcl_cs_decoder_set_fatal(ctx->decoder);
        return;
    }

    if (!vcl_cs_decoder_get_fatal(ctx->decoder))
        ctx->dispatch_clEnqueueCopyImage(ctx, &args);

#ifdef DEBUG
    if (!vcl_cs_decoder_get_fatal(ctx->decoder) && vcl_dispatch_should_log_result(args.ret))
        vcl_dispatch_debug_log(ctx, "clEnqueueCopyImage returned %d", args.ret);
#endif

    if ((flags & CL_COMMAND_GENERATE_REPLY_BIT_EXT) && !vcl_cs_decoder_get_fatal(ctx->decoder))
        vcl_encode_clEnqueueCopyImage_reply(ctx->encoder, &args);

    vcl_cs_decoder_reset_temp_pool(ctx->decoder);
#else
    vcl_dispatch_debug_log(ctx, "CL_API_SUFFIX__VERSION_1_0 not available for clEnqueueCopyImage");
    vcl_cs_decoder_set_fatal(ctx->decoder);
#endif // CL_API_SUFFIX__VERSION_1_0
}


static inline void vcl_dispatch_clEnqueueCopyImageToBuffer(struct vcl_dispatch_context *ctx, cl_command_flags_ext flags)
{
#ifdef CL_API_SUFFIX__VERSION_1_0
    struct vcl_command_clEnqueueCopyImageToBuffer args;

    if (!ctx->dispatch_clEnqueueCopyImageToBuffer) {
        vcl_cs_decoder_set_fatal(ctx->decoder);
        return;
    }

    vcl_decode_clEnqueueCopyImageToBuffer_args_temp(ctx->decoder, &args);
    if (!args.command_queue) {
        vcl_cs_decoder_set_fatal(ctx->decoder);
        return;
    }

    if (!vcl_cs_decoder_get_fatal(ctx->decoder))
        ctx->dispatch_clEnqueueCopyImageToBuffer(ctx, &args);

#ifdef DEBUG
    if (!vcl_cs_decoder_get_fatal(ctx->decoder) && vcl_dispatch_should_log_result(args.ret))
        vcl_dispatch_debug_log(ctx, "clEnqueueCopyImageToBuffer returned %d", args.ret);
#endif

    if ((flags & CL_COMMAND_GENERATE_REPLY_BIT_EXT) && !vcl_cs_decoder_get_fatal(ctx->decoder))
        vcl_encode_clEnqueueCopyImageToBuffer_reply(ctx->encoder, &args);

    vcl_cs_decoder_reset_temp_pool(ctx->decoder);
#else
    vcl_dispatch_debug_log(ctx, "CL_API_SUFFIX__VERSION_1_0 not available for clEnqueueCopyImageToBuffer");
    vcl_cs_decoder_set_fatal(ctx->decoder);
#endif // CL_API_SUFFIX__VERSION_1_0
}


static inline void vcl_dispatch_clEnqueueCopyBufferToImage(struct vcl_dispatch_context *ctx, cl_command_flags_ext flags)
{
#ifdef CL_API_SUFFIX__VERSION_1_0
    struct vcl_command_clEnqueueCopyBufferToImage args;

    if (!ctx->dispatch_clEnqueueCopyBufferToImage) {
        vcl_cs_decoder_set_fatal(ctx->decoder);
        return;
    }

    vcl_decode_clEnqueueCopyBufferToImage_args_temp(ctx->decoder, &args);
    if (!args.command_queue) {
        vcl_cs_decoder_set_fatal(ctx->decoder);
        return;
    }

    if (!vcl_cs_decoder_get_fatal(ctx->decoder))
        ctx->dispatch_clEnqueueCopyBufferToImage(ctx, &args);

#ifdef DEBUG
    if (!vcl_cs_decoder_get_fatal(ctx->decoder) && vcl_dispatch_should_log_result(args.ret))
        vcl_dispatch_debug_log(ctx, "clEnqueueCopyBufferToImage returned %d", args.ret);
#endif

    if ((flags & CL_COMMAND_GENERATE_REPLY_BIT_EXT) && !vcl_cs_decoder_get_fatal(ctx->decoder))
        vcl_encode_clEnqueueCopyBufferToImage_reply(ctx->encoder, &args);

    vcl_cs_decoder_reset_temp_pool(ctx->decoder);
#else
    vcl_dispatch_debug_log(ctx, "CL_API_SUFFIX__VERSION_1_0 not available for clEnqueueCopyBufferToImage");
    vcl_cs_decoder_set_fatal(ctx->decoder);
#endif // CL_API_SUFFIX__VERSION_1_0
}


static inline void vcl_dispatch_clCreateImageMESA(struct vcl_dispatch_context *ctx, cl_command_flags_ext flags)
{
#ifdef CL_API_SUFFIX__VERSION_1_2
    struct vcl_command_clCreateImageMESA args;

    if (!ctx->dispatch_clCreateImageMESA) {
        vcl_cs_decoder_set_fatal(ctx->decoder);
        return;
    }

    vcl_decode_clCreateImageMESA_args_temp(ctx->decoder, &args);
    if (!args.context) {
        vcl_cs_decoder_set_fatal(ctx->decoder);
        return;
    }

    if (!vcl_cs_decoder_get_fatal(ctx->decoder))
        ctx->dispatch_clCreateImageMESA(ctx, &args);

#ifdef DEBUG
    if (!vcl_cs_decoder_get_fatal(ctx->decoder) && vcl_dispatch_should_log_result(args.ret))
        vcl_dispatch_debug_log(ctx, "clCreateImageMESA returned %d", args.ret);
#endif

    if ((flags & CL_COMMAND_GENERATE_REPLY_BIT_EXT) && !vcl_cs_decoder_get_fatal(ctx->decoder))
        vcl_encode_clCreateImageMESA_reply(ctx->encoder, &args);

    vcl_cs_decoder_reset_temp_pool(ctx->decoder);
#else
    vcl_dispatch_debug_log(ctx, "CL_API_SUFFIX__VERSION_1_2 not available for clCreateImageMESA");
    vcl_cs_decoder_set_fatal(ctx->decoder);
#endif // CL_API_SUFFIX__VERSION_1_2
}


static inline void vcl_dispatch_clCreateImageWithPropertiesMESA(struct vcl_dispatch_context *ctx, cl_command_flags_ext flags)
{
#ifdef CL_API_SUFFIX__VERSION_3_0
    struct vcl_command_clCreateImageWithPropertiesMESA args;

    if (!ctx->dispatch_clCreateImageWithPropertiesMESA) {
        vcl_cs_decoder_set_fatal(ctx->decoder);
        return;
    }

    vcl_decode_clCreateImageWithPropertiesMESA_args_temp(ctx->decoder, &args);
    if (!args.context) {
        vcl_cs_decoder_set_fatal(ctx->decoder);
        return;
    }

    if (!vcl_cs_decoder_get_fatal(ctx->decoder))
        ctx->dispatch_clCreateImageWithPropertiesMESA(ctx, &args);

#ifdef DEBUG
    if (!vcl_cs_decoder_get_fatal(ctx->decoder) && vcl_dispatch_should_log_result(args.ret))
        vcl_dispatch_debug_log(ctx, "clCreateImageWithPropertiesMESA returned %d", args.ret);
#endif

    if ((flags & CL_COMMAND_GENERATE_REPLY_BIT_EXT) && !vcl_cs_decoder_get_fatal(ctx->decoder))
        vcl_encode_clCreateImageWithPropertiesMESA_reply(ctx->encoder, &args);

    vcl_cs_decoder_reset_temp_pool(ctx->decoder);
#else
    vcl_dispatch_debug_log(ctx, "CL_API_SUFFIX__VERSION_3_0 not available for clCreateImageWithPropertiesMESA");
    vcl_cs_decoder_set_fatal(ctx->decoder);
#endif // CL_API_SUFFIX__VERSION_3_0
}

#pragma GCC diagnostic pop

#endif /* VCL_PROTOCOL_RENDERER_IMAGE_H */
