/* This file is generated by vqnn-protocol.  See vqnn_protocol_renderer.h. */

/*
 * Copyright 2020 Google LLC
 * Copyright 2024 Qualcomm Innovation Center, Inc. All Rights Reserved.
 * SPDX-License-Identifier: MIT
 */

#ifndef VCL_PROTOCOL_RENDERER_CONTEXT_H
#define VCL_PROTOCOL_RENDERER_CONTEXT_H

#include "vqnn_protocol_renderer_structs.h"

#pragma GCC diagnostic push
#if !defined(__clang__) && defined(__GNUC__) && __GNUC__ >= 12
#pragma GCC diagnostic ignored "-Wdangling-pointer"
#endif
#pragma GCC diagnostic ignored "-Wpointer-arith"
#pragma GCC diagnostic ignored "-Wunused-parameter"

#ifdef CL_API_SUFFIX__VERSION_2_0
static inline void vcl_decode_clQnnContextFree_args_temp(struct vcl_cs_decoder *dec, struct vcl_command_clQnnContextFree *args)
{
    vcl_decode_Qnn_ContextHandle_t_lookup(dec, &args->context);
    vcl_decode_Qnn_ProfileHandle_t_lookup(dec, &args->profile);
}
#endif // CL_API_SUFFIX__VERSION_2_0

#ifdef CL_API_SUFFIX__VERSION_2_0
static inline void vcl_replace_clQnnContextFree_args_handle(struct vcl_command_clQnnContextFree *args)
{
    vcl_replace_Qnn_ContextHandle_t_handle(&args->context);
    vcl_replace_Qnn_ProfileHandle_t_handle(&args->profile);
}
#endif // CL_API_SUFFIX__VERSION_2_0

#ifdef CL_API_SUFFIX__VERSION_2_0
static inline void vcl_encode_clQnnContextFree_reply(struct vcl_cs_encoder *enc, const struct vcl_command_clQnnContextFree *args)
{
    vcl_encode_cl_command_type_ext(enc, &(cl_command_type_ext){CL_COMMAND_TYPE_clQnnContextFree_EXT});

    vcl_encode_Qnn_ErrorHandle_t(enc, &args->ret);
    /* skip args->context */
    /* skip args->profile */
}
#endif // CL_API_SUFFIX__VERSION_2_0

#ifdef CL_API_SUFFIX__VERSION_2_0
static inline void vcl_decode_clQnnBufferDataTransfer_args_temp(struct vcl_cs_decoder *dec, struct vcl_command_clQnnBufferDataTransfer *args)
{
    vcl_decode_int32_t(dec, &args->mem_ptr);
    vcl_decode_uint64_t(dec, &args->initial_data_size);
    vcl_decode_uint64_t(dec, &args->curr_size);
}
#endif // CL_API_SUFFIX__VERSION_2_0

#ifdef CL_API_SUFFIX__VERSION_2_0
static inline void vcl_replace_clQnnBufferDataTransfer_args_handle(struct vcl_command_clQnnBufferDataTransfer *args)
{
    /* skip args->mem_ptr */
    /* skip args->initial_data_size */
    /* skip args->curr_size */
}
#endif // CL_API_SUFFIX__VERSION_2_0

#ifdef CL_API_SUFFIX__VERSION_2_0
static inline void vcl_encode_clQnnBufferDataTransfer_reply(struct vcl_cs_encoder *enc, const struct vcl_command_clQnnBufferDataTransfer *args)
{
    vcl_encode_cl_command_type_ext(enc, &(cl_command_type_ext){CL_COMMAND_TYPE_clQnnBufferDataTransfer_EXT});

    vcl_encode_Qnn_ErrorHandle_t(enc, &args->ret);
    /* skip args->mem_ptr */
    /* skip args->initial_data_size */
    /* skip args->curr_size */
}
#endif // CL_API_SUFFIX__VERSION_2_0

#ifdef CL_API_SUFFIX__VERSION_2_0
static inline void vcl_decode_clQnnContextCreateFromBinaryMESA_args_temp(struct vcl_cs_decoder *dec, struct vcl_command_clQnnContextCreateFromBinaryMESA *args)
{
    vcl_decode_Qnn_BackendHandle_t_lookup(dec, &args->backend);
    vcl_decode_Qnn_DeviceHandle_t_lookup(dec, &args->device);
    vcl_decode_Qnn_ContextBinarySize_t(dec, &args->binaryBufferSize);
    if (vcl_decode_simple_pointer(dec)) {
        args->context = vcl_cs_decoder_alloc_temp(dec, sizeof(*args->context));
        if (!args->context) return;
        vcl_decode_Qnn_ContextHandle_t_temp(dec, args->context);
    } else {
        args->context = NULL;
        vcl_cs_decoder_set_fatal(dec);
    }
    vcl_decode_Qnn_ProfileHandle_t_lookup(dec, &args->profile);
}
#endif // CL_API_SUFFIX__VERSION_2_0

#ifdef CL_API_SUFFIX__VERSION_2_0
static inline void vcl_replace_clQnnContextCreateFromBinaryMESA_args_handle(struct vcl_command_clQnnContextCreateFromBinaryMESA *args)
{
    vcl_replace_Qnn_BackendHandle_t_handle(&args->backend);
    vcl_replace_Qnn_DeviceHandle_t_handle(&args->device);
    /* skip args->binaryBufferSize */
    /* skip args->context */
    vcl_replace_Qnn_ProfileHandle_t_handle(&args->profile);
}
#endif // CL_API_SUFFIX__VERSION_2_0

#ifdef CL_API_SUFFIX__VERSION_2_0
static inline void vcl_encode_clQnnContextCreateFromBinaryMESA_reply(struct vcl_cs_encoder *enc, const struct vcl_command_clQnnContextCreateFromBinaryMESA *args)
{
    vcl_encode_cl_command_type_ext(enc, &(cl_command_type_ext){CL_COMMAND_TYPE_clQnnContextCreateFromBinaryMESA_EXT});

    vcl_encode_Qnn_ErrorHandle_t(enc, &args->ret);
    /* skip args->backend */
    /* skip args->device */
    /* skip args->binaryBufferSize */
    if (vcl_encode_simple_pointer(enc, args->context))
        vcl_encode_Qnn_ContextHandle_t(enc, args->context);
    /* skip args->profile */
}
#endif // CL_API_SUFFIX__VERSION_2_0


static inline void vcl_dispatch_clQnnContextFree(struct vcl_dispatch_context *ctx, cl_command_flags_ext flags)
{
#ifdef CL_API_SUFFIX__VERSION_2_0
    struct vcl_command_clQnnContextFree args;

    if (!ctx->dispatch_clQnnContextFree) {
        vcl_cs_decoder_set_fatal(ctx->decoder);
        return;
    }

    vcl_decode_clQnnContextFree_args_temp(ctx->decoder, &args);
    if (!args.context) {
        vcl_cs_decoder_set_fatal(ctx->decoder);
        return;
    }

    if (!vcl_cs_decoder_get_fatal(ctx->decoder))
        ctx->dispatch_clQnnContextFree(ctx, &args);

    if ((flags & CL_COMMAND_GENERATE_REPLY_BIT_EXT) && !vcl_cs_decoder_get_fatal(ctx->decoder))
        vcl_encode_clQnnContextFree_reply(ctx->encoder, &args);

    vcl_cs_decoder_reset_temp_pool(ctx->decoder);
#else
    vcl_dispatch_debug_log(ctx, "CL_API_SUFFIX__VERSION_2_0 not available for clQnnContextFree");
    vcl_cs_decoder_set_fatal(ctx->decoder);
#endif // CL_API_SUFFIX__VERSION_2_0
}


static inline void vcl_dispatch_clQnnBufferDataTransfer(struct vcl_dispatch_context *ctx, cl_command_flags_ext flags)
{
#ifdef CL_API_SUFFIX__VERSION_2_0
    struct vcl_command_clQnnBufferDataTransfer args;

    if (!ctx->dispatch_clQnnBufferDataTransfer) {
        vcl_cs_decoder_set_fatal(ctx->decoder);
        return;
    }

    vcl_decode_clQnnBufferDataTransfer_args_temp(ctx->decoder, &args);

    if (!vcl_cs_decoder_get_fatal(ctx->decoder))
        ctx->dispatch_clQnnBufferDataTransfer(ctx, &args);

    if ((flags & CL_COMMAND_GENERATE_REPLY_BIT_EXT) && !vcl_cs_decoder_get_fatal(ctx->decoder))
        vcl_encode_clQnnBufferDataTransfer_reply(ctx->encoder, &args);

    vcl_cs_decoder_reset_temp_pool(ctx->decoder);
#else
    vcl_dispatch_debug_log(ctx, "CL_API_SUFFIX__VERSION_2_0 not available for clQnnBufferDataTransfer");
    vcl_cs_decoder_set_fatal(ctx->decoder);
#endif // CL_API_SUFFIX__VERSION_2_0
}


static inline void vcl_dispatch_clQnnContextCreateFromBinaryMESA(struct vcl_dispatch_context *ctx, cl_command_flags_ext flags)
{
#ifdef CL_API_SUFFIX__VERSION_2_0
    struct vcl_command_clQnnContextCreateFromBinaryMESA args;

    if (!ctx->dispatch_clQnnContextCreateFromBinaryMESA) {
        vcl_cs_decoder_set_fatal(ctx->decoder);
        return;
    }

    vcl_decode_clQnnContextCreateFromBinaryMESA_args_temp(ctx->decoder, &args);
    if (!args.backend) {
        vcl_cs_decoder_set_fatal(ctx->decoder);
        return;
    }

    if (!vcl_cs_decoder_get_fatal(ctx->decoder))
        ctx->dispatch_clQnnContextCreateFromBinaryMESA(ctx, &args);

    if ((flags & CL_COMMAND_GENERATE_REPLY_BIT_EXT) && !vcl_cs_decoder_get_fatal(ctx->decoder))
        vcl_encode_clQnnContextCreateFromBinaryMESA_reply(ctx->encoder, &args);

    vcl_cs_decoder_reset_temp_pool(ctx->decoder);
#else
    vcl_dispatch_debug_log(ctx, "CL_API_SUFFIX__VERSION_2_0 not available for clQnnContextCreateFromBinaryMESA");
    vcl_cs_decoder_set_fatal(ctx->decoder);
#endif // CL_API_SUFFIX__VERSION_2_0
}

#pragma GCC diagnostic pop

#endif /* VCL_PROTOCOL_RENDERER_CONTEXT_H */
