/* This file is generated by vqnn-protocol.  See vqnn_protocol_renderer.h. */

/*
 * Copyright 2020 Google LLC
 * Copyright 2024 Qualcomm Innovation Center, Inc. All Rights Reserved.
 * SPDX-License-Identifier: MIT
 */

#ifndef VCL_PROTOCOL_RENDERER_BACKEND_H
#define VCL_PROTOCOL_RENDERER_BACKEND_H

#include "vqnn_protocol_renderer_structs.h"

#pragma GCC diagnostic push
#if !defined(__clang__) && defined(__GNUC__) && __GNUC__ >= 12
#pragma GCC diagnostic ignored "-Wdangling-pointer"
#endif
#pragma GCC diagnostic ignored "-Wpointer-arith"
#pragma GCC diagnostic ignored "-Wunused-parameter"

#ifdef CL_API_SUFFIX__VERSION_2_0
static inline void vcl_decode_clQnnBackendFree_args_temp(struct vcl_cs_decoder *dec, struct vcl_command_clQnnBackendFree *args)
{
    vcl_decode_Qnn_BackendHandle_t_lookup(dec, &args->backend);
}
#endif // CL_API_SUFFIX__VERSION_2_0

#ifdef CL_API_SUFFIX__VERSION_2_0
static inline void vcl_replace_clQnnBackendFree_args_handle(struct vcl_command_clQnnBackendFree *args)
{
    vcl_replace_Qnn_BackendHandle_t_handle(&args->backend);
}
#endif // CL_API_SUFFIX__VERSION_2_0

#ifdef CL_API_SUFFIX__VERSION_2_0
static inline void vcl_encode_clQnnBackendFree_reply(struct vcl_cs_encoder *enc, const struct vcl_command_clQnnBackendFree *args)
{
    vcl_encode_cl_command_type_ext(enc, &(cl_command_type_ext){CL_COMMAND_TYPE_clQnnBackendFree_EXT});

    vcl_encode_Qnn_ErrorHandle_t(enc, &args->ret);
    /* skip args->backend */
}
#endif // CL_API_SUFFIX__VERSION_2_0

#ifdef CL_API_SUFFIX__VERSION_2_0
static inline void vcl_decode_clQnnBackendGetBuildId_args_temp(struct vcl_cs_decoder *dec, struct vcl_command_clQnnBackendGetBuildId *args)
{
    vcl_decode_uint64_t(dec, &args->id_size);
    if (vcl_peek_array_size(dec)) {
        const size_t array_size = vcl_decode_array_size(dec, args->id_size);
        args->id = vcl_cs_decoder_alloc_temp(dec, array_size);
        if (!args->id) return;
    } else {
        vcl_decode_array_size_unchecked(dec);
        args->id = NULL;
    }
    if (vcl_decode_simple_pointer(dec)) {
        args->ret_id_size = vcl_cs_decoder_alloc_temp(dec, sizeof(*args->ret_id_size));
        if (!args->ret_id_size) return;
    } else {
        args->ret_id_size = NULL;
    }
}
#endif // CL_API_SUFFIX__VERSION_2_0

#ifdef CL_API_SUFFIX__VERSION_2_0
static inline void vcl_replace_clQnnBackendGetBuildId_args_handle(struct vcl_command_clQnnBackendGetBuildId *args)
{
    /* skip args->id_size */
    /* skip args->id */
    /* skip args->ret_id_size */
}
#endif // CL_API_SUFFIX__VERSION_2_0

#ifdef CL_API_SUFFIX__VERSION_2_0
static inline void vcl_encode_clQnnBackendGetBuildId_reply(struct vcl_cs_encoder *enc, const struct vcl_command_clQnnBackendGetBuildId *args)
{
    vcl_encode_cl_command_type_ext(enc, &(cl_command_type_ext){CL_COMMAND_TYPE_clQnnBackendGetBuildId_EXT});

    vcl_encode_Qnn_ErrorHandle_t(enc, &args->ret);
    /* skip args->id_size */
    if (args->id) {
        vcl_encode_array_size(enc, args->id_size);
        vcl_encode_blob_array(enc, args->id, args->id_size);
    } else {
        vcl_encode_array_size(enc, 0);
    }
    if (vcl_encode_simple_pointer(enc, args->ret_id_size))
        vcl_encode_uint64_t(enc, args->ret_id_size);
}
#endif // CL_API_SUFFIX__VERSION_2_0

#ifdef CL_API_SUFFIX__VERSION_2_0
static inline void vcl_decode_clQnnBackendCreateMESA_args_temp(struct vcl_cs_decoder *dec, struct vcl_command_clQnnBackendCreateMESA *args)
{
    vcl_decode_Qnn_LogHandle_t_lookup(dec, &args->logger);
    if (vcl_decode_simple_pointer(dec)) {
        args->backend = vcl_cs_decoder_alloc_temp(dec, sizeof(*args->backend));
        if (!args->backend) return;
        vcl_decode_Qnn_BackendHandle_t_temp(dec, args->backend);
    } else {
        args->backend = NULL;
        vcl_cs_decoder_set_fatal(dec);
    }
}
#endif // CL_API_SUFFIX__VERSION_2_0

#ifdef CL_API_SUFFIX__VERSION_2_0
static inline void vcl_replace_clQnnBackendCreateMESA_args_handle(struct vcl_command_clQnnBackendCreateMESA *args)
{
    vcl_replace_Qnn_LogHandle_t_handle(&args->logger);
    /* skip args->backend */
}
#endif // CL_API_SUFFIX__VERSION_2_0

#ifdef CL_API_SUFFIX__VERSION_2_0
static inline void vcl_encode_clQnnBackendCreateMESA_reply(struct vcl_cs_encoder *enc, const struct vcl_command_clQnnBackendCreateMESA *args)
{
    vcl_encode_cl_command_type_ext(enc, &(cl_command_type_ext){CL_COMMAND_TYPE_clQnnBackendCreateMESA_EXT});

    vcl_encode_Qnn_ErrorHandle_t(enc, &args->ret);
    /* skip args->logger */
    if (vcl_encode_simple_pointer(enc, args->backend))
        vcl_encode_Qnn_BackendHandle_t(enc, args->backend);
}
#endif // CL_API_SUFFIX__VERSION_2_0


static inline void vcl_dispatch_clQnnBackendFree(struct vcl_dispatch_context *ctx, cl_command_flags_ext flags)
{
#ifdef CL_API_SUFFIX__VERSION_2_0
    struct vcl_command_clQnnBackendFree args;

    if (!ctx->dispatch_clQnnBackendFree) {
        vcl_cs_decoder_set_fatal(ctx->decoder);
        return;
    }

    vcl_decode_clQnnBackendFree_args_temp(ctx->decoder, &args);
    if (!args.backend) {
        vcl_cs_decoder_set_fatal(ctx->decoder);
        return;
    }

    if (!vcl_cs_decoder_get_fatal(ctx->decoder))
        ctx->dispatch_clQnnBackendFree(ctx, &args);

    if ((flags & CL_COMMAND_GENERATE_REPLY_BIT_EXT) && !vcl_cs_decoder_get_fatal(ctx->decoder))
        vcl_encode_clQnnBackendFree_reply(ctx->encoder, &args);

    vcl_cs_decoder_reset_temp_pool(ctx->decoder);
#else
    vcl_dispatch_debug_log(ctx, "CL_API_SUFFIX__VERSION_2_0 not available for clQnnBackendFree");
    vcl_cs_decoder_set_fatal(ctx->decoder);
#endif // CL_API_SUFFIX__VERSION_2_0
}


static inline void vcl_dispatch_clQnnBackendGetBuildId(struct vcl_dispatch_context *ctx, cl_command_flags_ext flags)
{
#ifdef CL_API_SUFFIX__VERSION_2_0
    struct vcl_command_clQnnBackendGetBuildId args;

    if (!ctx->dispatch_clQnnBackendGetBuildId) {
        vcl_cs_decoder_set_fatal(ctx->decoder);
        return;
    }

    vcl_decode_clQnnBackendGetBuildId_args_temp(ctx->decoder, &args);

    if (!vcl_cs_decoder_get_fatal(ctx->decoder))
        ctx->dispatch_clQnnBackendGetBuildId(ctx, &args);

    if ((flags & CL_COMMAND_GENERATE_REPLY_BIT_EXT) && !vcl_cs_decoder_get_fatal(ctx->decoder))
        vcl_encode_clQnnBackendGetBuildId_reply(ctx->encoder, &args);

    vcl_cs_decoder_reset_temp_pool(ctx->decoder);
#else
    vcl_dispatch_debug_log(ctx, "CL_API_SUFFIX__VERSION_2_0 not available for clQnnBackendGetBuildId");
    vcl_cs_decoder_set_fatal(ctx->decoder);
#endif // CL_API_SUFFIX__VERSION_2_0
}


static inline void vcl_dispatch_clQnnBackendCreateMESA(struct vcl_dispatch_context *ctx, cl_command_flags_ext flags)
{
#ifdef CL_API_SUFFIX__VERSION_2_0
    struct vcl_command_clQnnBackendCreateMESA args;

    if (!ctx->dispatch_clQnnBackendCreateMESA) {
        vcl_cs_decoder_set_fatal(ctx->decoder);
        return;
    }

    vcl_decode_clQnnBackendCreateMESA_args_temp(ctx->decoder, &args);
    if (!args.logger) {
        vcl_cs_decoder_set_fatal(ctx->decoder);
        return;
    }

    if (!vcl_cs_decoder_get_fatal(ctx->decoder))
        ctx->dispatch_clQnnBackendCreateMESA(ctx, &args);

    if ((flags & CL_COMMAND_GENERATE_REPLY_BIT_EXT) && !vcl_cs_decoder_get_fatal(ctx->decoder))
        vcl_encode_clQnnBackendCreateMESA_reply(ctx->encoder, &args);

    vcl_cs_decoder_reset_temp_pool(ctx->decoder);
#else
    vcl_dispatch_debug_log(ctx, "CL_API_SUFFIX__VERSION_2_0 not available for clQnnBackendCreateMESA");
    vcl_cs_decoder_set_fatal(ctx->decoder);
#endif // CL_API_SUFFIX__VERSION_2_0
}

#pragma GCC diagnostic pop

#endif /* VCL_PROTOCOL_RENDERER_BACKEND_H */
