/* This file is generated by venus-protocol git-fa94d313. */

/*
 * Copyright 2020 Google LLC
 * Copyright 2024 Qualcomm Innovation Center, Inc. All Rights Reserved.
 * SPDX-License-Identifier: MIT
 */

#ifndef VCL_PROTOCOL_RENDERER_H
#define VCL_PROTOCOL_RENDERER_H

#include "vqnn_protocol_renderer_cs.h"
#include "vqnn_protocol_renderer_defines.h"
#include "vqnn_protocol_renderer_func_ptrs.h"
#include "vqnn_protocol_renderer_info.h"
#include "vqnn_protocol_renderer_types.h"
#include "vqnn_protocol_renderer_handles.h"
#include "vqnn_protocol_renderer_dispatches.h"
#include "vqnn_protocol_renderer_structs.h"
#include "vqnn_protocol_renderer_dummy.h"
#include "vqnn_protocol_renderer_transport.h"
#include "vqnn_protocol_renderer_backend.h"
#include "vqnn_protocol_renderer_logger.h"
#include "vqnn_protocol_renderer_context.h"
#include "vqnn_protocol_renderer_graph.h"
#include "vqnn_protocol_renderer_property.h"

#endif /* VCL_PROTOCOL_RENDERER_H */
