/* This file is generated by vqnn-protocol.  See vqnn_protocol_renderer.h. */

/*
 * Copyright 2020 Google LLC
 * Copyright 2024 Qualcomm Innovation Center, Inc. All Rights Reserved.
 * SPDX-License-Identifier: MIT
 */

#ifndef VCL_PROTOCOL_RENDERER_LOGGER_H
#define VCL_PROTOCOL_RENDERER_LOGGER_H

#include "vqnn_protocol_renderer_structs.h"

#pragma GCC diagnostic push
#if !defined(__clang__) && defined(__GNUC__) && __GNUC__ >= 12
#pragma GCC diagnostic ignored "-Wdangling-pointer"
#endif
#pragma GCC diagnostic ignored "-Wpointer-arith"
#pragma GCC diagnostic ignored "-Wunused-parameter"

#ifdef CL_API_SUFFIX__VERSION_2_0
static inline void vcl_decode_clQnnLogCreate_args_temp(struct vcl_cs_decoder *dec, struct vcl_command_clQnnLogCreate *args)
{
    if (vcl_decode_simple_pointer(dec)) {
        vcl_cs_decoder_set_fatal(dec);
    } else {
        args->callback = NULL;
    }
    vcl_decode_QnnLog_Level_t(dec, &args->maxLogLevel);
    if (vcl_decode_simple_pointer(dec)) {
        args->logger = vcl_cs_decoder_alloc_temp(dec, sizeof(*args->logger));
        if (!args->logger) return;
        vcl_decode_Qnn_LogHandle_t_temp(dec, args->logger);
    } else {
        args->logger = NULL;
        vcl_cs_decoder_set_fatal(dec);
    }
}
#endif // CL_API_SUFFIX__VERSION_2_0

#ifdef CL_API_SUFFIX__VERSION_2_0
static inline void vcl_replace_clQnnLogCreate_args_handle(struct vcl_command_clQnnLogCreate *args)
{
    /* skip args->callback */
    /* skip args->maxLogLevel */
    /* skip args->logger */
}
#endif // CL_API_SUFFIX__VERSION_2_0

#ifdef CL_API_SUFFIX__VERSION_2_0
static inline void vcl_encode_clQnnLogCreate_reply(struct vcl_cs_encoder *enc, const struct vcl_command_clQnnLogCreate *args)
{
    vcl_encode_cl_command_type_ext(enc, &(cl_command_type_ext){CL_COMMAND_TYPE_clQnnLogCreate_EXT});

    vcl_encode_Qnn_ErrorHandle_t(enc, &args->ret);
    if (vcl_encode_simple_pointer(enc, args->callback))
        assert(false);
    /* skip args->maxLogLevel */
    if (vcl_encode_simple_pointer(enc, args->logger))
        vcl_encode_Qnn_LogHandle_t(enc, args->logger);
}
#endif // CL_API_SUFFIX__VERSION_2_0

#ifdef CL_API_SUFFIX__VERSION_2_0
static inline void vcl_decode_clQnnLogSetLogLevel_args_temp(struct vcl_cs_decoder *dec, struct vcl_command_clQnnLogSetLogLevel *args)
{
    vcl_decode_Qnn_LogHandle_t_lookup(dec, &args->logger);
    vcl_decode_QnnLog_Level_t(dec, &args->maxLogLevel);
}
#endif // CL_API_SUFFIX__VERSION_2_0

#ifdef CL_API_SUFFIX__VERSION_2_0
static inline void vcl_replace_clQnnLogSetLogLevel_args_handle(struct vcl_command_clQnnLogSetLogLevel *args)
{
    vcl_replace_Qnn_LogHandle_t_handle(&args->logger);
    /* skip args->maxLogLevel */
}
#endif // CL_API_SUFFIX__VERSION_2_0

#ifdef CL_API_SUFFIX__VERSION_2_0
static inline void vcl_encode_clQnnLogSetLogLevel_reply(struct vcl_cs_encoder *enc, const struct vcl_command_clQnnLogSetLogLevel *args)
{
    vcl_encode_cl_command_type_ext(enc, &(cl_command_type_ext){CL_COMMAND_TYPE_clQnnLogSetLogLevel_EXT});

    vcl_encode_Qnn_ErrorHandle_t(enc, &args->ret);
    /* skip args->logger */
    /* skip args->maxLogLevel */
}
#endif // CL_API_SUFFIX__VERSION_2_0

#ifdef CL_API_SUFFIX__VERSION_2_0
static inline void vcl_decode_clQnnLogFree_args_temp(struct vcl_cs_decoder *dec, struct vcl_command_clQnnLogFree *args)
{
    vcl_decode_Qnn_LogHandle_t_lookup(dec, &args->logger);
}
#endif // CL_API_SUFFIX__VERSION_2_0

#ifdef CL_API_SUFFIX__VERSION_2_0
static inline void vcl_replace_clQnnLogFree_args_handle(struct vcl_command_clQnnLogFree *args)
{
    vcl_replace_Qnn_LogHandle_t_handle(&args->logger);
}
#endif // CL_API_SUFFIX__VERSION_2_0

#ifdef CL_API_SUFFIX__VERSION_2_0
static inline void vcl_encode_clQnnLogFree_reply(struct vcl_cs_encoder *enc, const struct vcl_command_clQnnLogFree *args)
{
    vcl_encode_cl_command_type_ext(enc, &(cl_command_type_ext){CL_COMMAND_TYPE_clQnnLogFree_EXT});

    vcl_encode_Qnn_ErrorHandle_t(enc, &args->ret);
    /* skip args->logger */
}
#endif // CL_API_SUFFIX__VERSION_2_0


static inline void vcl_dispatch_clQnnLogCreate(struct vcl_dispatch_context *ctx, cl_command_flags_ext flags)
{
#ifdef CL_API_SUFFIX__VERSION_2_0
    struct vcl_command_clQnnLogCreate args;

    if (!ctx->dispatch_clQnnLogCreate) {
        vcl_cs_decoder_set_fatal(ctx->decoder);
        return;
    }

    vcl_decode_clQnnLogCreate_args_temp(ctx->decoder, &args);

    if (!vcl_cs_decoder_get_fatal(ctx->decoder))
        ctx->dispatch_clQnnLogCreate(ctx, &args);

    if ((flags & CL_COMMAND_GENERATE_REPLY_BIT_EXT) && !vcl_cs_decoder_get_fatal(ctx->decoder))
        vcl_encode_clQnnLogCreate_reply(ctx->encoder, &args);

    vcl_cs_decoder_reset_temp_pool(ctx->decoder);
#else
    vcl_dispatch_debug_log(ctx, "CL_API_SUFFIX__VERSION_2_0 not available for clQnnLogCreate");
    vcl_cs_decoder_set_fatal(ctx->decoder);
#endif // CL_API_SUFFIX__VERSION_2_0
}


static inline void vcl_dispatch_clQnnLogSetLogLevel(struct vcl_dispatch_context *ctx, cl_command_flags_ext flags)
{
#ifdef CL_API_SUFFIX__VERSION_2_0
    struct vcl_command_clQnnLogSetLogLevel args;

    if (!ctx->dispatch_clQnnLogSetLogLevel) {
        vcl_cs_decoder_set_fatal(ctx->decoder);
        return;
    }

    vcl_decode_clQnnLogSetLogLevel_args_temp(ctx->decoder, &args);
    if (!args.logger) {
        vcl_cs_decoder_set_fatal(ctx->decoder);
        return;
    }

    if (!vcl_cs_decoder_get_fatal(ctx->decoder))
        ctx->dispatch_clQnnLogSetLogLevel(ctx, &args);

    if ((flags & CL_COMMAND_GENERATE_REPLY_BIT_EXT) && !vcl_cs_decoder_get_fatal(ctx->decoder))
        vcl_encode_clQnnLogSetLogLevel_reply(ctx->encoder, &args);

    vcl_cs_decoder_reset_temp_pool(ctx->decoder);
#else
    vcl_dispatch_debug_log(ctx, "CL_API_SUFFIX__VERSION_2_0 not available for clQnnLogSetLogLevel");
    vcl_cs_decoder_set_fatal(ctx->decoder);
#endif // CL_API_SUFFIX__VERSION_2_0
}


static inline void vcl_dispatch_clQnnLogFree(struct vcl_dispatch_context *ctx, cl_command_flags_ext flags)
{
#ifdef CL_API_SUFFIX__VERSION_2_0
    struct vcl_command_clQnnLogFree args;

    if (!ctx->dispatch_clQnnLogFree) {
        vcl_cs_decoder_set_fatal(ctx->decoder);
        return;
    }

    vcl_decode_clQnnLogFree_args_temp(ctx->decoder, &args);
    if (!args.logger) {
        vcl_cs_decoder_set_fatal(ctx->decoder);
        return;
    }

    if (!vcl_cs_decoder_get_fatal(ctx->decoder))
        ctx->dispatch_clQnnLogFree(ctx, &args);

    if ((flags & CL_COMMAND_GENERATE_REPLY_BIT_EXT) && !vcl_cs_decoder_get_fatal(ctx->decoder))
        vcl_encode_clQnnLogFree_reply(ctx->encoder, &args);

    vcl_cs_decoder_reset_temp_pool(ctx->decoder);
#else
    vcl_dispatch_debug_log(ctx, "CL_API_SUFFIX__VERSION_2_0 not available for clQnnLogFree");
    vcl_cs_decoder_set_fatal(ctx->decoder);
#endif // CL_API_SUFFIX__VERSION_2_0
}

#pragma GCC diagnostic pop

#endif /* VCL_PROTOCOL_RENDERER_LOGGER_H */
