/* This file is generated by vqnn-protocol.  See vqnn_protocol_renderer.h. */

/*
 * Copyright 2020 Google LLC
 * Copyright 2024 Qualcomm Innovation Center, Inc. All Rights Reserved.
 * SPDX-License-Identifier: MIT
 */

#ifndef VCL_PROTOCOL_RENDERER_DEFINES_H
#define VCL_PROTOCOL_RENDERER_DEFINES_H

#include <stdarg.h>
#include <stdlib.h>
#include <string.h>
#include <stdio.h>

#include <QNN/QnnInterface.h>

#include "vqnn_protocol_renderer_cs.h"
#include "vqnn_protocol_renderer_func_ptrs.h"

typedef enum cl_command_type_ext {
    CL_COMMAND_TYPE_clQnnBackendFree_EXT = 151,
    CL_COMMAND_TYPE_clQnnLogCreate_EXT = 152,
    CL_COMMAND_TYPE_clQnnLogSetLogLevel_EXT = 153,
    CL_COMMAND_TYPE_clQnnLogFree_EXT = 154,
    CL_COMMAND_TYPE_clQnnContextCreateFromBinary_EXT = 155,
    CL_COMMAND_TYPE_clQnnContextFree_EXT = 156,
    CL_COMMAND_TYPE_clQnnGraphRetrieve_EXT = 157,
    CL_COMMAND_TYPE_clQnnGraphExecute_EXT = 158,
    CL_COMMAND_TYPE_clQnnPropertyHasCapability_EXT = 159,
    CL_COMMAND_TYPE_clQnnBackendGetBuildId_EXT = 160,
    CL_COMMAND_TYPE_clQnnBufferDataTransfer_EXT = 165,
    CL_COMMAND_TYPE_clQnnGraphRetrieveMESA_EXT = 161,
    CL_COMMAND_TYPE_clQnnContextCreateFromBinaryMESA_EXT = 162,
    CL_COMMAND_TYPE_clQnnBackendCreateMESA_EXT = 163,
    CL_COMMAND_TYPE_clSetReplyBufferMESA_EXT = 164,
} cl_command_type_ext;

typedef enum cl_command_flag_bits_ext {
    Empty = 0x00000000,
    CL_COMMAND_GENERATE_REPLY_BIT_EXT = 0x00000001,
} cl_command_flag_bits_ext;

typedef uint32_t cl_command_flags_ext;

struct vcl_command_clQnnBackendFree {
#ifdef CL_API_SUFFIX__VERSION_2_0
    Qnn_BackendHandle_t backend;
    
    Qnn_ErrorHandle_t ret;
#else //
#endif // CL_API_SUFFIX__VERSION_2_0
};

struct vcl_command_clQnnLogCreate {
#ifdef CL_API_SUFFIX__VERSION_2_0
    void* callback;
    QnnLog_Level_t maxLogLevel;
    Qnn_LogHandle_t* logger;
    
    Qnn_ErrorHandle_t ret;
#else //
#endif // CL_API_SUFFIX__VERSION_2_0
};

struct vcl_command_clQnnLogSetLogLevel {
#ifdef CL_API_SUFFIX__VERSION_2_0
    Qnn_LogHandle_t logger;
    QnnLog_Level_t maxLogLevel;
    
    Qnn_ErrorHandle_t ret;
#else //
#endif // CL_API_SUFFIX__VERSION_2_0
};

struct vcl_command_clQnnLogFree {
#ifdef CL_API_SUFFIX__VERSION_2_0
    Qnn_LogHandle_t logger;
    
    Qnn_ErrorHandle_t ret;
#else //
#endif // CL_API_SUFFIX__VERSION_2_0
};

struct vcl_command_clQnnContextCreateFromBinary {
#ifdef CL_API_SUFFIX__VERSION_2_0
    Qnn_BackendHandle_t backend;
    Qnn_DeviceHandle_t device;
    const void** config;
    uint64_t config_size;
    uint64_t config_count;
    const void* binaryBuffer;
    Qnn_ContextBinarySize_t binaryBufferSize;
    Qnn_ContextHandle_t* context;
    uint64_t profile;
    
    Qnn_ErrorHandle_t ret;
#else //
#endif // CL_API_SUFFIX__VERSION_2_0
};

struct vcl_command_clQnnContextFree {
#ifdef CL_API_SUFFIX__VERSION_2_0
    Qnn_ContextHandle_t context;
    Qnn_ProfileHandle_t profile;
    
    Qnn_ErrorHandle_t ret;
#else //
#endif // CL_API_SUFFIX__VERSION_2_0
};

struct vcl_command_clQnnGraphRetrieve {
#ifdef CL_API_SUFFIX__VERSION_2_0
    Qnn_ContextHandle_t contextHandle;
    void* graphName;
    Qnn_GraphHandle_t* graphHandle;
    
    Qnn_ErrorHandle_t ret;
#else //
#endif // CL_API_SUFFIX__VERSION_2_0
};

struct vcl_command_clQnnGraphExecute {
#ifdef CL_API_SUFFIX__VERSION_2_0
    Qnn_GraphHandle_t graphHandle;
    int32_t mem_ptr;
    uint32_t numInputs;
    uint32_t numOutputs;
    Qnn_ProfileHandle_t profileHandle;
    Qnn_SignalHandle_t signalHandle;
    
    Qnn_ErrorHandle_t ret;
#else //
#endif // CL_API_SUFFIX__VERSION_2_0
};

struct vcl_command_clQnnPropertyHasCapability {
#ifdef CL_API_SUFFIX__VERSION_2_0
    QnnProperty_Key_t key;
    
    Qnn_ErrorHandle_t ret;
#else //
#endif // CL_API_SUFFIX__VERSION_2_0
};

struct vcl_command_clQnnBackendGetBuildId {
#ifdef CL_API_SUFFIX__VERSION_2_0
    uint64_t id_size;
    void* id;
    uint64_t* ret_id_size;
    
    Qnn_ErrorHandle_t ret;
#else //
#endif // CL_API_SUFFIX__VERSION_2_0
};

struct vcl_command_clQnnBufferDataTransfer {
#ifdef CL_API_SUFFIX__VERSION_2_0
    int32_t mem_ptr;
    uint64_t initial_data_size;
    uint64_t curr_size;
    
    Qnn_ErrorHandle_t ret;
#else //
#endif // CL_API_SUFFIX__VERSION_2_0
};

struct vcl_command_clSetReplyBufferMESA {
    int32_t resource_id;
    
};

struct vcl_command_clQnnBackendCreateMESA {
#ifdef CL_API_SUFFIX__VERSION_2_0
    Qnn_LogHandle_t logger;
    Qnn_BackendHandle_t* backend;
    
    Qnn_ErrorHandle_t ret;
#else //
#endif // CL_API_SUFFIX__VERSION_2_0
};

struct vcl_command_clQnnContextCreateFromBinaryMESA {
#ifdef CL_API_SUFFIX__VERSION_2_0
    Qnn_BackendHandle_t backend;
    Qnn_DeviceHandle_t device;
    Qnn_ContextBinarySize_t binaryBufferSize;
    Qnn_ContextHandle_t* context;
    Qnn_ProfileHandle_t profile;
    
    Qnn_ErrorHandle_t ret;
#else //
#endif // CL_API_SUFFIX__VERSION_2_0
};

struct vcl_command_clQnnGraphRetrieveMESA {
#ifdef CL_API_SUFFIX__VERSION_2_0
    Qnn_ContextHandle_t contextHandle;
    const char* graphName;
    Qnn_GraphHandle_t* graphHandle;
    
    Qnn_ErrorHandle_t ret;
#else //
#endif // CL_API_SUFFIX__VERSION_2_0
};

struct vcl_dispatch_context {
    void *data;
    void (*debug_log)(struct vcl_dispatch_context *ctx, const char *msg);

    struct vcl_cs_encoder *encoder;
    struct vcl_cs_decoder *decoder;

    void (*dispatch_clQnnBackendFree)(struct vcl_dispatch_context *ctx, struct vcl_command_clQnnBackendFree *args);
    void (*dispatch_clQnnLogCreate)(struct vcl_dispatch_context *ctx, struct vcl_command_clQnnLogCreate *args);
    void (*dispatch_clQnnLogSetLogLevel)(struct vcl_dispatch_context *ctx, struct vcl_command_clQnnLogSetLogLevel *args);
    void (*dispatch_clQnnLogFree)(struct vcl_dispatch_context *ctx, struct vcl_command_clQnnLogFree *args);
    void (*dispatch_clQnnContextCreateFromBinary)(struct vcl_dispatch_context *ctx, struct vcl_command_clQnnContextCreateFromBinary *args);
    void (*dispatch_clQnnContextFree)(struct vcl_dispatch_context *ctx, struct vcl_command_clQnnContextFree *args);
    void (*dispatch_clQnnGraphRetrieve)(struct vcl_dispatch_context *ctx, struct vcl_command_clQnnGraphRetrieve *args);
    void (*dispatch_clQnnGraphExecute)(struct vcl_dispatch_context *ctx, struct vcl_command_clQnnGraphExecute *args);
    void (*dispatch_clQnnPropertyHasCapability)(struct vcl_dispatch_context *ctx, struct vcl_command_clQnnPropertyHasCapability *args);
    void (*dispatch_clQnnBackendGetBuildId)(struct vcl_dispatch_context *ctx, struct vcl_command_clQnnBackendGetBuildId *args);
    void (*dispatch_clQnnBufferDataTransfer)(struct vcl_dispatch_context *ctx, struct vcl_command_clQnnBufferDataTransfer *args);
    void (*dispatch_clSetReplyBufferMESA)(struct vcl_dispatch_context *ctx, struct vcl_command_clSetReplyBufferMESA *args);
    void (*dispatch_clQnnBackendCreateMESA)(struct vcl_dispatch_context *ctx, struct vcl_command_clQnnBackendCreateMESA *args);
    void (*dispatch_clQnnContextCreateFromBinaryMESA)(struct vcl_dispatch_context *ctx, struct vcl_command_clQnnContextCreateFromBinaryMESA *args);
    void (*dispatch_clQnnGraphRetrieveMESA)(struct vcl_dispatch_context *ctx, struct vcl_command_clQnnGraphRetrieveMESA *args);
};

static inline void vcl_dispatch_debug_log(struct vcl_dispatch_context *ctx, const char *format, ...)
{
    char msg[256];
    va_list va;

    if (!ctx->debug_log)
        return;

    va_start(va, format);
    vsnprintf(msg, sizeof(msg), format, va);
    ctx->debug_log(ctx, msg);
    va_end(va);
}

static inline bool vcl_dispatch_should_log_result(int32_t result)
{
    switch (result) {
    default:
        /* log all other errors */
        return result < 0;
    }
}

#endif /* VCL_PROTOCOL_RENDERER_DEFINES_H */
