/* This file is generated by vqnn-protocol.  See vqnn_protocol_renderer.h. */

/*
 * Copyright 2020 Google LLC
 * Copyright 2024 Qualcomm Innovation Center, Inc. All Rights Reserved.
 * SPDX-License-Identifier: MIT
 */

#ifndef VCL_PROTOCOL_RENDERER_PROPERTY_H
#define VCL_PROTOCOL_RENDERER_PROPERTY_H

#include "vqnn_protocol_renderer_structs.h"

#pragma GCC diagnostic push
#if !defined(__clang__) && defined(__GNUC__) && __GNUC__ >= 12
#pragma GCC diagnostic ignored "-Wdangling-pointer"
#endif
#pragma GCC diagnostic ignored "-Wpointer-arith"
#pragma GCC diagnostic ignored "-Wunused-parameter"

#ifdef CL_API_SUFFIX__VERSION_2_0
static inline void vcl_decode_clQnnPropertyHasCapability_args_temp(struct vcl_cs_decoder *dec, struct vcl_command_clQnnPropertyHasCapability *args)
{
    vcl_decode_QnnProperty_Key_t(dec, &args->key);
}
#endif // CL_API_SUFFIX__VERSION_2_0

#ifdef CL_API_SUFFIX__VERSION_2_0
static inline void vcl_replace_clQnnPropertyHasCapability_args_handle(struct vcl_command_clQnnPropertyHasCapability *args)
{
    /* skip args->key */
}
#endif // CL_API_SUFFIX__VERSION_2_0

#ifdef CL_API_SUFFIX__VERSION_2_0
static inline void vcl_encode_clQnnPropertyHasCapability_reply(struct vcl_cs_encoder *enc, const struct vcl_command_clQnnPropertyHasCapability *args)
{
    vcl_encode_cl_command_type_ext(enc, &(cl_command_type_ext){CL_COMMAND_TYPE_clQnnPropertyHasCapability_EXT});

    vcl_encode_Qnn_ErrorHandle_t(enc, &args->ret);
    /* skip args->key */
}
#endif // CL_API_SUFFIX__VERSION_2_0


static inline void vcl_dispatch_clQnnPropertyHasCapability(struct vcl_dispatch_context *ctx, cl_command_flags_ext flags)
{
#ifdef CL_API_SUFFIX__VERSION_2_0
    struct vcl_command_clQnnPropertyHasCapability args;

    if (!ctx->dispatch_clQnnPropertyHasCapability) {
        vcl_cs_decoder_set_fatal(ctx->decoder);
        return;
    }

    vcl_decode_clQnnPropertyHasCapability_args_temp(ctx->decoder, &args);

    if (!vcl_cs_decoder_get_fatal(ctx->decoder))
        ctx->dispatch_clQnnPropertyHasCapability(ctx, &args);

    if ((flags & CL_COMMAND_GENERATE_REPLY_BIT_EXT) && !vcl_cs_decoder_get_fatal(ctx->decoder))
        vcl_encode_clQnnPropertyHasCapability_reply(ctx->encoder, &args);

    vcl_cs_decoder_reset_temp_pool(ctx->decoder);
#else
    vcl_dispatch_debug_log(ctx, "CL_API_SUFFIX__VERSION_2_0 not available for clQnnPropertyHasCapability");
    vcl_cs_decoder_set_fatal(ctx->decoder);
#endif // CL_API_SUFFIX__VERSION_2_0
}

#pragma GCC diagnostic pop

#endif /* VCL_PROTOCOL_RENDERER_PROPERTY_H */
