/* This file is generated by vqnn-protocol.  See vqnn_protocol_renderer.h. */

/*
 * Copyright 2020 Google LLC
 * Copyright 2024 Qualcomm Innovation Center, Inc. All Rights Reserved.
 * SPDX-License-Identifier: MIT
 */

#ifndef VCL_PROTOCOL_RENDERER_DUMMY_H
#define VCL_PROTOCOL_RENDERER_DUMMY_H

#include "vqnn_protocol_renderer_structs.h"

#pragma GCC diagnostic push
#if !defined(__clang__) && defined(__GNUC__) && __GNUC__ >= 12
#pragma GCC diagnostic ignored "-Wdangling-pointer"
#endif
#pragma GCC diagnostic ignored "-Wpointer-arith"
#pragma GCC diagnostic ignored "-Wunused-parameter"

#ifdef CL_API_SUFFIX__VERSION_2_0
static inline void vcl_decode_clQnnContextCreateFromBinary_args_temp(struct vcl_cs_decoder *dec, struct vcl_command_clQnnContextCreateFromBinary *args)
{
    vcl_decode_Qnn_BackendHandle_t_lookup(dec, &args->backend);
    vcl_decode_Qnn_DeviceHandle_t_lookup(dec, &args->device);
    if (vcl_peek_array_size(dec)) {
        for (uint64_t i = 0; i < args->config_count; i++)
            vcl_cs_decoder_set_fatal(dec);
    } else {
        vcl_decode_array_size_unchecked(dec);
        args->config = NULL;
    }
    vcl_decode_uint64_t(dec, &args->config_size);
    vcl_decode_uint64_t(dec, &args->config_count);
    if (vcl_peek_array_size(dec)) {
        const size_t array_size = vcl_decode_array_size(dec, args->binaryBufferSize);
        args->binaryBuffer = vcl_cs_decoder_alloc_temp(dec, array_size);
        if (!args->binaryBuffer) return;
        vcl_decode_blob_array(dec, (void *)args->binaryBuffer, array_size);
    } else {
        vcl_decode_array_size(dec, args->binaryBufferSize);
        args->binaryBuffer = NULL;
    }
    vcl_decode_Qnn_ContextBinarySize_t(dec, &args->binaryBufferSize);
    if (vcl_decode_simple_pointer(dec)) {
        args->context = vcl_cs_decoder_alloc_temp(dec, sizeof(*args->context));
        if (!args->context) return;
        vcl_decode_Qnn_ContextHandle_t_temp(dec, args->context);
    } else {
        args->context = NULL;
        vcl_cs_decoder_set_fatal(dec);
    }
    vcl_decode_uint64_t(dec, &args->profile);
}
#endif // CL_API_SUFFIX__VERSION_2_0

#ifdef CL_API_SUFFIX__VERSION_2_0
static inline void vcl_replace_clQnnContextCreateFromBinary_args_handle(struct vcl_command_clQnnContextCreateFromBinary *args)
{
    vcl_replace_Qnn_BackendHandle_t_handle(&args->backend);
    vcl_replace_Qnn_DeviceHandle_t_handle(&args->device);
    /* skip args->config */
    /* skip args->config_size */
    /* skip args->config_count */
    /* skip args->binaryBuffer */
    /* skip args->binaryBufferSize */
    /* skip args->context */
    /* skip args->profile */
}
#endif // CL_API_SUFFIX__VERSION_2_0

#ifdef CL_API_SUFFIX__VERSION_2_0
static inline void vcl_encode_clQnnContextCreateFromBinary_reply(struct vcl_cs_encoder *enc, const struct vcl_command_clQnnContextCreateFromBinary *args)
{
    vcl_encode_cl_command_type_ext(enc, &(cl_command_type_ext){CL_COMMAND_TYPE_clQnnContextCreateFromBinary_EXT});

    vcl_encode_Qnn_ErrorHandle_t(enc, &args->ret);
    /* skip args->backend */
    /* skip args->device */
    /* skip args->config */
    /* skip args->config_size */
    /* skip args->config_count */
    /* skip args->binaryBuffer */
    /* skip args->binaryBufferSize */
    if (vcl_encode_simple_pointer(enc, args->context))
        vcl_encode_Qnn_ContextHandle_t(enc, args->context);
    /* skip args->profile */
}
#endif // CL_API_SUFFIX__VERSION_2_0

#ifdef CL_API_SUFFIX__VERSION_2_0
static inline void vcl_decode_clQnnGraphRetrieve_args_temp(struct vcl_cs_decoder *dec, struct vcl_command_clQnnGraphRetrieve *args)
{
    vcl_decode_Qnn_ContextHandle_t_lookup(dec, &args->contextHandle);
    if (vcl_decode_simple_pointer(dec)) {
        vcl_cs_decoder_set_fatal(dec);
    } else {
        args->graphName = NULL;
    }
    if (vcl_decode_simple_pointer(dec)) {
        args->graphHandle = vcl_cs_decoder_alloc_temp(dec, sizeof(*args->graphHandle));
        if (!args->graphHandle) return;
        vcl_decode_Qnn_GraphHandle_t_temp(dec, args->graphHandle);
    } else {
        args->graphHandle = NULL;
        vcl_cs_decoder_set_fatal(dec);
    }
}
#endif // CL_API_SUFFIX__VERSION_2_0

#ifdef CL_API_SUFFIX__VERSION_2_0
static inline void vcl_replace_clQnnGraphRetrieve_args_handle(struct vcl_command_clQnnGraphRetrieve *args)
{
    vcl_replace_Qnn_ContextHandle_t_handle(&args->contextHandle);
    /* skip args->graphName */
    /* skip args->graphHandle */
}
#endif // CL_API_SUFFIX__VERSION_2_0

#ifdef CL_API_SUFFIX__VERSION_2_0
static inline void vcl_encode_clQnnGraphRetrieve_reply(struct vcl_cs_encoder *enc, const struct vcl_command_clQnnGraphRetrieve *args)
{
    vcl_encode_cl_command_type_ext(enc, &(cl_command_type_ext){CL_COMMAND_TYPE_clQnnGraphRetrieve_EXT});

    vcl_encode_Qnn_ErrorHandle_t(enc, &args->ret);
    /* skip args->contextHandle */
    if (vcl_encode_simple_pointer(enc, args->graphName))
        assert(false);
    if (vcl_encode_simple_pointer(enc, args->graphHandle))
        vcl_encode_Qnn_GraphHandle_t(enc, args->graphHandle);
}
#endif // CL_API_SUFFIX__VERSION_2_0


static inline void vcl_dispatch_clQnnContextCreateFromBinary(struct vcl_dispatch_context *ctx, cl_command_flags_ext flags)
{
#ifdef CL_API_SUFFIX__VERSION_2_0
    struct vcl_command_clQnnContextCreateFromBinary args;

    if (!ctx->dispatch_clQnnContextCreateFromBinary) {
        vcl_cs_decoder_set_fatal(ctx->decoder);
        return;
    }

    vcl_decode_clQnnContextCreateFromBinary_args_temp(ctx->decoder, &args);
    if (!args.backend) {
        vcl_cs_decoder_set_fatal(ctx->decoder);
        return;
    }

    if (!vcl_cs_decoder_get_fatal(ctx->decoder))
        ctx->dispatch_clQnnContextCreateFromBinary(ctx, &args);

    if ((flags & CL_COMMAND_GENERATE_REPLY_BIT_EXT) && !vcl_cs_decoder_get_fatal(ctx->decoder))
        vcl_encode_clQnnContextCreateFromBinary_reply(ctx->encoder, &args);

    vcl_cs_decoder_reset_temp_pool(ctx->decoder);
#else
    vcl_dispatch_debug_log(ctx, "CL_API_SUFFIX__VERSION_2_0 not available for clQnnContextCreateFromBinary");
    vcl_cs_decoder_set_fatal(ctx->decoder);
#endif // CL_API_SUFFIX__VERSION_2_0
}


static inline void vcl_dispatch_clQnnGraphRetrieve(struct vcl_dispatch_context *ctx, cl_command_flags_ext flags)
{
#ifdef CL_API_SUFFIX__VERSION_2_0
    struct vcl_command_clQnnGraphRetrieve args;

    if (!ctx->dispatch_clQnnGraphRetrieve) {
        vcl_cs_decoder_set_fatal(ctx->decoder);
        return;
    }

    vcl_decode_clQnnGraphRetrieve_args_temp(ctx->decoder, &args);
    if (!args.contextHandle) {
        vcl_cs_decoder_set_fatal(ctx->decoder);
        return;
    }

    if (!vcl_cs_decoder_get_fatal(ctx->decoder))
        ctx->dispatch_clQnnGraphRetrieve(ctx, &args);

    if ((flags & CL_COMMAND_GENERATE_REPLY_BIT_EXT) && !vcl_cs_decoder_get_fatal(ctx->decoder))
        vcl_encode_clQnnGraphRetrieve_reply(ctx->encoder, &args);

    vcl_cs_decoder_reset_temp_pool(ctx->decoder);
#else
    vcl_dispatch_debug_log(ctx, "CL_API_SUFFIX__VERSION_2_0 not available for clQnnGraphRetrieve");
    vcl_cs_decoder_set_fatal(ctx->decoder);
#endif // CL_API_SUFFIX__VERSION_2_0
}

#pragma GCC diagnostic pop

#endif /* VCL_PROTOCOL_RENDERER_DUMMY_H */
