/* This file is generated by vqnn-protocol.  See vqnn_protocol_renderer.h. */

/*
 * Copyright 2020 Google LLC
 * Copyright 2024 Qualcomm Innovation Center, Inc. All Rights Reserved.
 * SPDX-License-Identifier: MIT
 */

#ifndef VCL_PROTOCOL_RENDERER_GRAPH_H
#define VCL_PROTOCOL_RENDERER_GRAPH_H

#include "vqnn_protocol_renderer_structs.h"

#pragma GCC diagnostic push
#if !defined(__clang__) && defined(__GNUC__) && __GNUC__ >= 12
#pragma GCC diagnostic ignored "-Wdangling-pointer"
#endif
#pragma GCC diagnostic ignored "-Wpointer-arith"
#pragma GCC diagnostic ignored "-Wunused-parameter"

#ifdef CL_API_SUFFIX__VERSION_2_0
static inline void vcl_decode_clQnnGraphExecute_args_temp(struct vcl_cs_decoder *dec, struct vcl_command_clQnnGraphExecute *args)
{
    vcl_decode_Qnn_GraphHandle_t_lookup(dec, &args->graphHandle);
    vcl_decode_int32_t(dec, &args->mem_ptr);
    vcl_decode_uint32_t(dec, &args->numInputs);
    vcl_decode_uint32_t(dec, &args->numOutputs);
    vcl_decode_Qnn_ProfileHandle_t_lookup(dec, &args->profileHandle);
    vcl_decode_Qnn_SignalHandle_t_lookup(dec, &args->signalHandle);
}
#endif // CL_API_SUFFIX__VERSION_2_0

#ifdef CL_API_SUFFIX__VERSION_2_0
static inline void vcl_replace_clQnnGraphExecute_args_handle(struct vcl_command_clQnnGraphExecute *args)
{
    vcl_replace_Qnn_GraphHandle_t_handle(&args->graphHandle);
    /* skip args->mem_ptr */
    /* skip args->numInputs */
    /* skip args->numOutputs */
    vcl_replace_Qnn_ProfileHandle_t_handle(&args->profileHandle);
    vcl_replace_Qnn_SignalHandle_t_handle(&args->signalHandle);
}
#endif // CL_API_SUFFIX__VERSION_2_0

#ifdef CL_API_SUFFIX__VERSION_2_0
static inline void vcl_encode_clQnnGraphExecute_reply(struct vcl_cs_encoder *enc, const struct vcl_command_clQnnGraphExecute *args)
{
    vcl_encode_cl_command_type_ext(enc, &(cl_command_type_ext){CL_COMMAND_TYPE_clQnnGraphExecute_EXT});

    vcl_encode_Qnn_ErrorHandle_t(enc, &args->ret);
    /* skip args->graphHandle */
    /* skip args->mem_ptr */
    /* skip args->numInputs */
    /* skip args->numOutputs */
    /* skip args->profileHandle */
    /* skip args->signalHandle */
}
#endif // CL_API_SUFFIX__VERSION_2_0

#ifdef CL_API_SUFFIX__VERSION_2_0
static inline void vcl_decode_clQnnGraphRetrieveMESA_args_temp(struct vcl_cs_decoder *dec, struct vcl_command_clQnnGraphRetrieveMESA *args)
{
    vcl_decode_Qnn_ContextHandle_t_lookup(dec, &args->contextHandle);
    if (vcl_peek_array_size(dec)) {
        const size_t null_terminated_array_size = vcl_decode_array_size_unchecked(dec);
        args->graphName = vcl_cs_decoder_alloc_temp_array(dec, sizeof(*args->graphName), null_terminated_array_size);
        if (!args->graphName) return;
        vcl_decode_char_array(dec, (char *)args->graphName, null_terminated_array_size);
    } else {
        vcl_decode_array_size_unchecked(dec);
        args->graphName = NULL;
    }
    if (vcl_decode_simple_pointer(dec)) {
        args->graphHandle = vcl_cs_decoder_alloc_temp(dec, sizeof(*args->graphHandle));
        if (!args->graphHandle) return;
        vcl_decode_Qnn_GraphHandle_t_temp(dec, args->graphHandle);
    } else {
        args->graphHandle = NULL;
        vcl_cs_decoder_set_fatal(dec);
    }
}
#endif // CL_API_SUFFIX__VERSION_2_0

#ifdef CL_API_SUFFIX__VERSION_2_0
static inline void vcl_replace_clQnnGraphRetrieveMESA_args_handle(struct vcl_command_clQnnGraphRetrieveMESA *args)
{
    vcl_replace_Qnn_ContextHandle_t_handle(&args->contextHandle);
    /* skip args->graphName */
    /* skip args->graphHandle */
}
#endif // CL_API_SUFFIX__VERSION_2_0

#ifdef CL_API_SUFFIX__VERSION_2_0
static inline void vcl_encode_clQnnGraphRetrieveMESA_reply(struct vcl_cs_encoder *enc, const struct vcl_command_clQnnGraphRetrieveMESA *args)
{
    vcl_encode_cl_command_type_ext(enc, &(cl_command_type_ext){CL_COMMAND_TYPE_clQnnGraphRetrieveMESA_EXT});

    vcl_encode_Qnn_ErrorHandle_t(enc, &args->ret);
    /* skip args->contextHandle */
    /* skip args->graphName */
    if (vcl_encode_simple_pointer(enc, args->graphHandle))
        vcl_encode_Qnn_GraphHandle_t(enc, args->graphHandle);
}
#endif // CL_API_SUFFIX__VERSION_2_0


static inline void vcl_dispatch_clQnnGraphExecute(struct vcl_dispatch_context *ctx, cl_command_flags_ext flags)
{
#ifdef CL_API_SUFFIX__VERSION_2_0
    struct vcl_command_clQnnGraphExecute args;

    if (!ctx->dispatch_clQnnGraphExecute) {
        vcl_cs_decoder_set_fatal(ctx->decoder);
        return;
    }

    vcl_decode_clQnnGraphExecute_args_temp(ctx->decoder, &args);
    if (!args.graphHandle) {
        vcl_cs_decoder_set_fatal(ctx->decoder);
        return;
    }

    if (!vcl_cs_decoder_get_fatal(ctx->decoder))
        ctx->dispatch_clQnnGraphExecute(ctx, &args);

    if ((flags & CL_COMMAND_GENERATE_REPLY_BIT_EXT) && !vcl_cs_decoder_get_fatal(ctx->decoder))
        vcl_encode_clQnnGraphExecute_reply(ctx->encoder, &args);

    vcl_cs_decoder_reset_temp_pool(ctx->decoder);
#else
    vcl_dispatch_debug_log(ctx, "CL_API_SUFFIX__VERSION_2_0 not available for clQnnGraphExecute");
    vcl_cs_decoder_set_fatal(ctx->decoder);
#endif // CL_API_SUFFIX__VERSION_2_0
}


static inline void vcl_dispatch_clQnnGraphRetrieveMESA(struct vcl_dispatch_context *ctx, cl_command_flags_ext flags)
{
#ifdef CL_API_SUFFIX__VERSION_2_0
    struct vcl_command_clQnnGraphRetrieveMESA args;

    if (!ctx->dispatch_clQnnGraphRetrieveMESA) {
        vcl_cs_decoder_set_fatal(ctx->decoder);
        return;
    }

    vcl_decode_clQnnGraphRetrieveMESA_args_temp(ctx->decoder, &args);
    if (!args.contextHandle) {
        vcl_cs_decoder_set_fatal(ctx->decoder);
        return;
    }

    if (!vcl_cs_decoder_get_fatal(ctx->decoder))
        ctx->dispatch_clQnnGraphRetrieveMESA(ctx, &args);

    if ((flags & CL_COMMAND_GENERATE_REPLY_BIT_EXT) && !vcl_cs_decoder_get_fatal(ctx->decoder))
        vcl_encode_clQnnGraphRetrieveMESA_reply(ctx->encoder, &args);

    vcl_cs_decoder_reset_temp_pool(ctx->decoder);
#else
    vcl_dispatch_debug_log(ctx, "CL_API_SUFFIX__VERSION_2_0 not available for clQnnGraphRetrieveMESA");
    vcl_cs_decoder_set_fatal(ctx->decoder);
#endif // CL_API_SUFFIX__VERSION_2_0
}

#pragma GCC diagnostic pop

#endif /* VCL_PROTOCOL_RENDERER_GRAPH_H */
