/* This file is generated by vqnn-protocol.  See vqnn_protocol_renderer.h. */

/*
 * Copyright 2020 Google LLC
 * Copyright 2024 Qualcomm Innovation Center, Inc. All Rights Reserved.
 * SPDX-License-Identifier: MIT
 */

#ifndef VCL_PROTOCOL_RENDERER_HANDLES_H
#define VCL_PROTOCOL_RENDERER_HANDLES_H

#include "vqnn_protocol_renderer_types.h"

/* VK_DEFINE_HANDLE(Qnn_LogHandle_t) */

static inline void
vcl_encode_Qnn_LogHandle_t(struct vcl_cs_encoder *enc, const Qnn_LogHandle_t *val)
{
    const uint64_t id = vcl_cs_handle_load_id((const void **)val);
    vcl_encode_uint64_t(enc, &id);
}

static inline void
vcl_decode_Qnn_LogHandle_t_temp(struct vcl_cs_decoder *dec, Qnn_LogHandle_t *val)
{
    uint64_t id;
    vcl_decode_uint64_t(dec, &id);
    vcl_cs_handle_store_id((void **)val, id);
}

static inline void
vcl_decode_Qnn_LogHandle_t_lookup(struct vcl_cs_decoder *dec, Qnn_LogHandle_t *val)
{
    uint64_t id;
    vcl_decode_uint64_t(dec, &id);
    *val = (Qnn_LogHandle_t)vcl_cs_decoder_lookup_object(dec, id);
}

static inline void
vcl_replace_Qnn_LogHandle_t_handle(Qnn_LogHandle_t *val)
{
    *val = (Qnn_LogHandle_t)(uintptr_t)vcl_cs_get_object_handle((const void **)val);
}

/* VK_DEFINE_HANDLE(Qnn_BackendHandle_t) */

static inline void
vcl_encode_Qnn_BackendHandle_t(struct vcl_cs_encoder *enc, const Qnn_BackendHandle_t *val)
{
    const uint64_t id = vcl_cs_handle_load_id((const void **)val);
    vcl_encode_uint64_t(enc, &id);
}

static inline void
vcl_decode_Qnn_BackendHandle_t_temp(struct vcl_cs_decoder *dec, Qnn_BackendHandle_t *val)
{
    uint64_t id;
    vcl_decode_uint64_t(dec, &id);
    vcl_cs_handle_store_id((void **)val, id);
}

static inline void
vcl_decode_Qnn_BackendHandle_t_lookup(struct vcl_cs_decoder *dec, Qnn_BackendHandle_t *val)
{
    uint64_t id;
    vcl_decode_uint64_t(dec, &id);
    *val = (Qnn_BackendHandle_t)vcl_cs_decoder_lookup_object(dec, id);
}

static inline void
vcl_replace_Qnn_BackendHandle_t_handle(Qnn_BackendHandle_t *val)
{
    *val = (Qnn_BackendHandle_t)(uintptr_t)vcl_cs_get_object_handle((const void **)val);
}

/* VK_DEFINE_HANDLE(Qnn_DeviceHandle_t) */

static inline void
vcl_encode_Qnn_DeviceHandle_t(struct vcl_cs_encoder *enc, const Qnn_DeviceHandle_t *val)
{
    const uint64_t id = vcl_cs_handle_load_id((const void **)val);
    vcl_encode_uint64_t(enc, &id);
}

static inline void
vcl_decode_Qnn_DeviceHandle_t_temp(struct vcl_cs_decoder *dec, Qnn_DeviceHandle_t *val)
{
    uint64_t id;
    vcl_decode_uint64_t(dec, &id);
    vcl_cs_handle_store_id((void **)val, id);
}

static inline void
vcl_decode_Qnn_DeviceHandle_t_lookup(struct vcl_cs_decoder *dec, Qnn_DeviceHandle_t *val)
{
    uint64_t id;
    vcl_decode_uint64_t(dec, &id);
    *val = (Qnn_DeviceHandle_t)vcl_cs_decoder_lookup_object(dec, id);
}

static inline void
vcl_replace_Qnn_DeviceHandle_t_handle(Qnn_DeviceHandle_t *val)
{
    *val = (Qnn_DeviceHandle_t)(uintptr_t)vcl_cs_get_object_handle((const void **)val);
}

/* VK_DEFINE_HANDLE(Qnn_ContextHandle_t) */

static inline void
vcl_encode_Qnn_ContextHandle_t(struct vcl_cs_encoder *enc, const Qnn_ContextHandle_t *val)
{
    const uint64_t id = vcl_cs_handle_load_id((const void **)val);
    vcl_encode_uint64_t(enc, &id);
}

static inline void
vcl_decode_Qnn_ContextHandle_t_temp(struct vcl_cs_decoder *dec, Qnn_ContextHandle_t *val)
{
    uint64_t id;
    vcl_decode_uint64_t(dec, &id);
    vcl_cs_handle_store_id((void **)val, id);
}

static inline void
vcl_decode_Qnn_ContextHandle_t_lookup(struct vcl_cs_decoder *dec, Qnn_ContextHandle_t *val)
{
    uint64_t id;
    vcl_decode_uint64_t(dec, &id);
    *val = (Qnn_ContextHandle_t)vcl_cs_decoder_lookup_object(dec, id);
}

static inline void
vcl_replace_Qnn_ContextHandle_t_handle(Qnn_ContextHandle_t *val)
{
    *val = (Qnn_ContextHandle_t)(uintptr_t)vcl_cs_get_object_handle((const void **)val);
}

/* VK_DEFINE_HANDLE(Qnn_ProfileHandle_t) */

static inline void
vcl_encode_Qnn_ProfileHandle_t(struct vcl_cs_encoder *enc, const Qnn_ProfileHandle_t *val)
{
    const uint64_t id = vcl_cs_handle_load_id((const void **)val);
    vcl_encode_uint64_t(enc, &id);
}

static inline void
vcl_decode_Qnn_ProfileHandle_t_temp(struct vcl_cs_decoder *dec, Qnn_ProfileHandle_t *val)
{
    uint64_t id;
    vcl_decode_uint64_t(dec, &id);
    vcl_cs_handle_store_id((void **)val, id);
}

static inline void
vcl_decode_Qnn_ProfileHandle_t_lookup(struct vcl_cs_decoder *dec, Qnn_ProfileHandle_t *val)
{
    uint64_t id;
    vcl_decode_uint64_t(dec, &id);
    *val = (Qnn_ProfileHandle_t)vcl_cs_decoder_lookup_object(dec, id);
}

static inline void
vcl_replace_Qnn_ProfileHandle_t_handle(Qnn_ProfileHandle_t *val)
{
    *val = (Qnn_ProfileHandle_t)(uintptr_t)vcl_cs_get_object_handle((const void **)val);
}

/* VK_DEFINE_HANDLE(Qnn_GraphHandle_t) */

static inline void
vcl_encode_Qnn_GraphHandle_t(struct vcl_cs_encoder *enc, const Qnn_GraphHandle_t *val)
{
    const uint64_t id = vcl_cs_handle_load_id((const void **)val);
    vcl_encode_uint64_t(enc, &id);
}

static inline void
vcl_decode_Qnn_GraphHandle_t_temp(struct vcl_cs_decoder *dec, Qnn_GraphHandle_t *val)
{
    uint64_t id;
    vcl_decode_uint64_t(dec, &id);
    vcl_cs_handle_store_id((void **)val, id);
}

static inline void
vcl_decode_Qnn_GraphHandle_t_lookup(struct vcl_cs_decoder *dec, Qnn_GraphHandle_t *val)
{
    uint64_t id;
    vcl_decode_uint64_t(dec, &id);
    *val = (Qnn_GraphHandle_t)vcl_cs_decoder_lookup_object(dec, id);
}

static inline void
vcl_replace_Qnn_GraphHandle_t_handle(Qnn_GraphHandle_t *val)
{
    *val = (Qnn_GraphHandle_t)(uintptr_t)vcl_cs_get_object_handle((const void **)val);
}

/* VK_DEFINE_HANDLE(Qnn_SignalHandle_t) */

static inline void
vcl_encode_Qnn_SignalHandle_t(struct vcl_cs_encoder *enc, const Qnn_SignalHandle_t *val)
{
    const uint64_t id = vcl_cs_handle_load_id((const void **)val);
    vcl_encode_uint64_t(enc, &id);
}

static inline void
vcl_decode_Qnn_SignalHandle_t_temp(struct vcl_cs_decoder *dec, Qnn_SignalHandle_t *val)
{
    uint64_t id;
    vcl_decode_uint64_t(dec, &id);
    vcl_cs_handle_store_id((void **)val, id);
}

static inline void
vcl_decode_Qnn_SignalHandle_t_lookup(struct vcl_cs_decoder *dec, Qnn_SignalHandle_t *val)
{
    uint64_t id;
    vcl_decode_uint64_t(dec, &id);
    *val = (Qnn_SignalHandle_t)vcl_cs_decoder_lookup_object(dec, id);
}

static inline void
vcl_replace_Qnn_SignalHandle_t_handle(Qnn_SignalHandle_t *val)
{
    *val = (Qnn_SignalHandle_t)(uintptr_t)vcl_cs_get_object_handle((const void **)val);
}

/* VK_DEFINE_HANDLE(QnnBackend_CustomConfig_t) */

static inline void
vcl_encode_QnnBackend_CustomConfig_t(struct vcl_cs_encoder *enc, const QnnBackend_CustomConfig_t *val)
{
    const uint64_t id = vcl_cs_handle_load_id((const void **)val);
    vcl_encode_uint64_t(enc, &id);
}

static inline void
vcl_decode_QnnBackend_CustomConfig_t_temp(struct vcl_cs_decoder *dec, QnnBackend_CustomConfig_t *val)
{
    uint64_t id;
    vcl_decode_uint64_t(dec, &id);
    vcl_cs_handle_store_id((void **)val, id);
}

static inline void
vcl_decode_QnnBackend_CustomConfig_t_lookup(struct vcl_cs_decoder *dec, QnnBackend_CustomConfig_t *val)
{
    uint64_t id;
    vcl_decode_uint64_t(dec, &id);
    *val = (QnnBackend_CustomConfig_t)vcl_cs_decoder_lookup_object(dec, id);
}

static inline void
vcl_replace_QnnBackend_CustomConfig_t_handle(QnnBackend_CustomConfig_t *val)
{
    *val = (QnnBackend_CustomConfig_t)(uintptr_t)vcl_cs_get_object_handle((const void **)val);
}

#endif /* VCL_PROTOCOL_RENDERER_HANDLES_H */
