/* This file is generated by vqnn-protocol.  See vqnn_protocol_renderer.h. */

/*
 * Copyright 2020 Google LLC
 * Copyright 2024 Qualcomm Innovation Center, Inc. All Rights Reserved.
 * SPDX-License-Identifier: MIT
 */

#ifndef VCL_PROTOCOL_RENDERER_TYPES_H
#define VCL_PROTOCOL_RENDERER_TYPES_H

#include "vqnn_protocol_renderer_defines.h"

/* char */

static inline void
vcl_encode_char(struct vcl_cs_encoder *enc, const char *val)
{
    vcl_encode(enc, 4, val, sizeof(*val));
}

static inline void
vcl_decode_char(struct vcl_cs_decoder *dec, char *val)
{
    vcl_decode(dec, 4, val, sizeof(*val));
}

/* uint64_t */

static inline void
vcl_encode_uint64_t(struct vcl_cs_encoder *enc, const uint64_t *val)
{
    vcl_encode(enc, 8, val, sizeof(*val));
}

static inline void
vcl_decode_uint64_t(struct vcl_cs_decoder *dec, uint64_t *val)
{
    vcl_decode(dec, 8, val, sizeof(*val));
}

static inline void
vcl_encode_uint64_t_array(struct vcl_cs_encoder *enc, const uint64_t *val, uint32_t count)
{
    const size_t size = sizeof(*val) * count;
    assert(size >= count);
    vcl_encode(enc, size, val, size);
}

static inline void
vcl_decode_uint64_t_array(struct vcl_cs_decoder *dec, uint64_t *val, uint32_t count)
{
    const size_t size = sizeof(*val) * count;
    assert(size >= count);
    vcl_decode(dec, size, val, size);
}

/* opaque blob */

static inline void
vcl_encode_blob_array(struct vcl_cs_encoder *enc, const void *val, size_t size)
{
    vcl_encode(enc, (size + 3) & ~3, val, size);
}

static inline void
vcl_decode_blob_array(struct vcl_cs_decoder *dec, void *val, size_t size)
{
    vcl_decode(dec, (size + 3) & ~3, val, size);
}

/* string */

static inline void
vcl_encode_char_array(struct vcl_cs_encoder *enc, const char *val, size_t size)
{
    assert(size && strlen(val) < size);
    vcl_encode_blob_array(enc, val, size);
}

static inline void
vcl_decode_char_array(struct vcl_cs_decoder *dec, char *val, size_t size)
{
    vcl_decode_blob_array(dec, val, size);
    if (size)
        val[size - 1] = '\0';
    else
        vcl_cs_decoder_set_fatal(dec);
}

/* array size (uint64_t) */

static inline void
vcl_encode_array_size(struct vcl_cs_encoder *enc, uint64_t size)
{
    vcl_encode_uint64_t(enc, &size);
}

static inline uint64_t
vcl_decode_array_size(struct vcl_cs_decoder *dec, uint64_t expected_size)
{
    uint64_t size;
    vcl_decode_uint64_t(dec, &size);
    if (size != expected_size) {
        vcl_cs_decoder_set_fatal(dec);
        size = 0;
    }
    return size;
}

static inline uint64_t
vcl_decode_array_size_unchecked(struct vcl_cs_decoder *dec)
{
    uint64_t size;
    vcl_decode_uint64_t(dec, &size);
    return size;
}

static inline uint64_t
vcl_peek_array_size(struct vcl_cs_decoder *dec)
{
    uint64_t size;
    vcl_cs_decoder_peek(dec, sizeof(size), &size, sizeof(size));
    return size;
}

/* non-array pointer */

static inline bool
vcl_encode_simple_pointer(struct vcl_cs_encoder *enc, const void *val)
{
    vcl_encode_array_size(enc, val ? 1 : 0);
    return val;
}

static inline bool
vcl_decode_simple_pointer(struct vcl_cs_decoder *dec)
{
    return vcl_decode_array_size_unchecked(dec);
}

/* uint32_t */

static inline void
vcl_encode_uint32_t(struct vcl_cs_encoder *enc, const uint32_t *val)
{
    vcl_encode(enc, 4, val, sizeof(*val));
}

static inline void
vcl_decode_uint32_t(struct vcl_cs_decoder *dec, uint32_t *val)
{
    vcl_decode(dec, 4, val, sizeof(*val));
}

/* int32_t */

static inline void
vcl_encode_int32_t(struct vcl_cs_encoder *enc, const int32_t *val)
{
    vcl_encode(enc, 4, val, sizeof(*val));
}

static inline void
vcl_decode_int32_t(struct vcl_cs_decoder *dec, int32_t *val)
{
    vcl_decode(dec, 4, val, sizeof(*val));
}

/* typedef uint32_t QnnProperty_Key_t */

static inline void
vcl_encode_QnnProperty_Key_t(struct vcl_cs_encoder *enc, const QnnProperty_Key_t *val)
{
    vcl_encode_uint32_t(enc, val);
}

static inline void
vcl_decode_QnnProperty_Key_t(struct vcl_cs_decoder *dec, QnnProperty_Key_t *val)
{
    vcl_decode_uint32_t(dec, val);
}

/* typedef uint64_t Qnn_ContextBinarySize_t */

static inline void
vcl_encode_Qnn_ContextBinarySize_t(struct vcl_cs_encoder *enc, const Qnn_ContextBinarySize_t *val)
{
    vcl_encode_uint64_t(enc, val);
}

static inline void
vcl_decode_Qnn_ContextBinarySize_t(struct vcl_cs_decoder *dec, Qnn_ContextBinarySize_t *val)
{
    vcl_decode_uint64_t(dec, val);
}

/* typedef uint64_t Qnn_ErrorHandle_t */

static inline void
vcl_encode_Qnn_ErrorHandle_t(struct vcl_cs_encoder *enc, const Qnn_ErrorHandle_t *val)
{
    vcl_encode_uint64_t(enc, val);
}

static inline void
vcl_decode_Qnn_ErrorHandle_t(struct vcl_cs_decoder *dec, Qnn_ErrorHandle_t *val)
{
    vcl_decode_uint64_t(dec, val);
}

/* enum Qnn_ErrorReportingLevel_t */

static inline void
vcl_encode_Qnn_ErrorReportingLevel_t(struct vcl_cs_encoder *enc, const Qnn_ErrorReportingLevel_t *val)
{
    vcl_encode_int32_t(enc, (const int32_t *)val);
}

static inline void
vcl_decode_Qnn_ErrorReportingLevel_t(struct vcl_cs_decoder *dec, Qnn_ErrorReportingLevel_t *val)
{
    vcl_decode_int32_t(dec, (int32_t *)val);
}

/* enum QnnBackend_ConfigOption_t */

static inline void
vcl_encode_QnnBackend_ConfigOption_t(struct vcl_cs_encoder *enc, const QnnBackend_ConfigOption_t *val)
{
    vcl_encode_int32_t(enc, (const int32_t *)val);
}

static inline void
vcl_decode_QnnBackend_ConfigOption_t(struct vcl_cs_decoder *dec, QnnBackend_ConfigOption_t *val)
{
    vcl_decode_int32_t(dec, (int32_t *)val);
}

/* enum QnnLog_Level_t */

static inline void
vcl_encode_QnnLog_Level_t(struct vcl_cs_encoder *enc, const QnnLog_Level_t *val)
{
    vcl_encode_int32_t(enc, (const int32_t *)val);
}

static inline void
vcl_decode_QnnLog_Level_t(struct vcl_cs_decoder *dec, QnnLog_Level_t *val)
{
    vcl_decode_int32_t(dec, (int32_t *)val);
}

/* enum cl_command_flag_bits_ext */

static inline void
vcl_encode_cl_command_flag_bits_ext(struct vcl_cs_encoder *enc, const cl_command_flag_bits_ext *val)
{
    vcl_encode_int32_t(enc, (const int32_t *)val);
}

static inline void
vcl_decode_cl_command_flag_bits_ext(struct vcl_cs_decoder *dec, cl_command_flag_bits_ext *val)
{
    vcl_decode_int32_t(dec, (int32_t *)val);
}

/* enum cl_command_type_ext */

static inline void
vcl_encode_cl_command_type_ext(struct vcl_cs_encoder *enc, const cl_command_type_ext *val)
{
    vcl_encode_int32_t(enc, (const int32_t *)val);
}

static inline void
vcl_decode_cl_command_type_ext(struct vcl_cs_decoder *dec, cl_command_type_ext *val)
{
    vcl_decode_int32_t(dec, (int32_t *)val);
}

#endif /* VCL_PROTOCOL_RENDERER_TYPES_H */
