/* This file is generated by vqnn-protocol.  See vqnn_protocol_renderer.h. */

/*
 * Copyright 2020 Google LLC
 * Copyright 2024 Qualcomm Innovation Center, Inc. All Rights Reserved.
 * SPDX-License-Identifier: MIT
 */

#ifndef VCL_PROTOCOL_RENDERER_DISPATCHES_H
#define VCL_PROTOCOL_RENDERER_DISPATCHES_H

#include "virgl_util.h"

#include "vqnn_protocol_renderer_structs.h"
#include "vqnn_protocol_renderer_dummy.h"
#include "vqnn_protocol_renderer_transport.h"
#include "vqnn_protocol_renderer_backend.h"
#include "vqnn_protocol_renderer_logger.h"
#include "vqnn_protocol_renderer_context.h"
#include "vqnn_protocol_renderer_graph.h"
#include "vqnn_protocol_renderer_property.h"

static inline const char *vcl_dispatch_command_name(cl_command_type_ext type)
{
    switch (type) {
    case CL_COMMAND_TYPE_clQnnBackendFree_EXT: return "clQnnBackendFree";
    case CL_COMMAND_TYPE_clQnnLogCreate_EXT: return "clQnnLogCreate";
    case CL_COMMAND_TYPE_clQnnLogSetLogLevel_EXT: return "clQnnLogSetLogLevel";
    case CL_COMMAND_TYPE_clQnnLogFree_EXT: return "clQnnLogFree";
    case CL_COMMAND_TYPE_clQnnContextCreateFromBinary_EXT: return "clQnnContextCreateFromBinary";
    case CL_COMMAND_TYPE_clQnnContextFree_EXT: return "clQnnContextFree";
    case CL_COMMAND_TYPE_clQnnGraphRetrieve_EXT: return "clQnnGraphRetrieve";
    case CL_COMMAND_TYPE_clQnnGraphExecute_EXT: return "clQnnGraphExecute";
    case CL_COMMAND_TYPE_clQnnPropertyHasCapability_EXT: return "clQnnPropertyHasCapability";
    case CL_COMMAND_TYPE_clQnnBackendGetBuildId_EXT: return "clQnnBackendGetBuildId";
    case CL_COMMAND_TYPE_clQnnBufferDataTransfer_EXT: return "clQnnBufferDataTransfer";
    case CL_COMMAND_TYPE_clSetReplyBufferMESA_EXT: return "clSetReplyBufferMESA";
    case CL_COMMAND_TYPE_clQnnBackendCreateMESA_EXT: return "clQnnBackendCreateMESA";
    case CL_COMMAND_TYPE_clQnnContextCreateFromBinaryMESA_EXT: return "clQnnContextCreateFromBinaryMESA";
    case CL_COMMAND_TYPE_clQnnGraphRetrieveMESA_EXT: return "clQnnGraphRetrieveMESA";
    default: return "unknown";
    }
}

static void (*const vcl_dispatch_table[166])(struct vcl_dispatch_context *ctx, cl_command_flags_ext flags) = {
    [CL_COMMAND_TYPE_clQnnBackendFree_EXT] = vcl_dispatch_clQnnBackendFree,
    [CL_COMMAND_TYPE_clQnnLogCreate_EXT] = vcl_dispatch_clQnnLogCreate,
    [CL_COMMAND_TYPE_clQnnLogSetLogLevel_EXT] = vcl_dispatch_clQnnLogSetLogLevel,
    [CL_COMMAND_TYPE_clQnnLogFree_EXT] = vcl_dispatch_clQnnLogFree,
    [CL_COMMAND_TYPE_clQnnContextCreateFromBinary_EXT] = vcl_dispatch_clQnnContextCreateFromBinary,
    [CL_COMMAND_TYPE_clQnnContextFree_EXT] = vcl_dispatch_clQnnContextFree,
    [CL_COMMAND_TYPE_clQnnGraphRetrieve_EXT] = vcl_dispatch_clQnnGraphRetrieve,
    [CL_COMMAND_TYPE_clQnnGraphExecute_EXT] = vcl_dispatch_clQnnGraphExecute,
    [CL_COMMAND_TYPE_clQnnPropertyHasCapability_EXT] = vcl_dispatch_clQnnPropertyHasCapability,
    [CL_COMMAND_TYPE_clQnnBackendGetBuildId_EXT] = vcl_dispatch_clQnnBackendGetBuildId,
    [CL_COMMAND_TYPE_clQnnBufferDataTransfer_EXT] = vcl_dispatch_clQnnBufferDataTransfer,
    [CL_COMMAND_TYPE_clSetReplyBufferMESA_EXT] = vcl_dispatch_clSetReplyBufferMESA,
    [CL_COMMAND_TYPE_clQnnBackendCreateMESA_EXT] = vcl_dispatch_clQnnBackendCreateMESA,
    [CL_COMMAND_TYPE_clQnnContextCreateFromBinaryMESA_EXT] = vcl_dispatch_clQnnContextCreateFromBinaryMESA,
    [CL_COMMAND_TYPE_clQnnGraphRetrieveMESA_EXT] = vcl_dispatch_clQnnGraphRetrieveMESA,
};

static inline void vcl_dispatch_command(struct vcl_dispatch_context *ctx)
{
    cl_command_type_ext cmd_type;
    cl_command_flags_ext cmd_flags;

    vcl_decode_cl_command_type_ext(ctx->decoder, &cmd_type);
    vcl_decode_cl_command_flag_bits_ext(ctx->decoder, &cmd_flags);

    {
#ifdef DEBUG
        TRACE_SCOPE_SLOW(vcl_dispatch_command_name(cmd_type));
#endif
        if (cmd_type < 166 && vcl_dispatch_table[cmd_type])
            vcl_dispatch_table[cmd_type](ctx, cmd_flags);
        else
            vcl_cs_decoder_set_fatal(ctx->decoder);
    }

    if (vcl_cs_decoder_get_fatal(ctx->decoder))
        vcl_dispatch_debug_log(ctx, "%s resulted in CS error", vcl_dispatch_command_name(cmd_type));
}

#endif /* VCL_PROTOCOL_RENDERER_DISPATCHES_H */
